import { date, name, internet, address } from 'faker/locale/en';

import { randomDate, weightedBoolean } from './utils';

export const generateCustomers = (): Customer[] => {
    // This is the total number of people pictures available. We only use those pictures for actual customers
    const maxCustomers = 223;
    let numberOfCustomers = 0;
    // let result = Array.from(Array(900).keys()).map(id => {
    //     const first_seen = randomDate();
    //     const last_seen = randomDate(first_seen);
    //     const has_ordered =
    //         weightedBoolean(25) && numberOfCustomers < maxCustomers;
    //     const first_name = name.firstName();
    //     const last_name = name.lastName();
    //     const email = internet.email(first_name, last_name);
    //     const birthday = has_ordered ? date.past(60) : null;
    //     const avatar = has_ordered
    //         ? 'https://marmelab.com/posters/avatar-' +
    //         numberOfCustomers +
    //         '.jpeg'
    //         : undefined;
    //
    //
    //     if (has_ordered) {
    //         numberOfCustomers++;
    //     }
    //
    //     return {
    //         id,
    //         first_name,
    //         last_name,
    //         email,
    //         address: has_ordered ? address.streetAddress() : null,
    //         zipcode: has_ordered ? address.zipCode() : null,
    //         city: has_ordered ? address.city() : null,
    //         stateAbbr: has_ordered ? address.stateAbbr() : null,
    //         avatar,
    //         birthday: birthday ? birthday.toISOString() : null,
    //         first_seen: first_seen.toISOString(),
    //         last_seen: last_seen.toISOString(),
    //         has_ordered: has_ordered,
    //         latest_purchase: null, // finalize
    //         has_newsletter: has_ordered ? weightedBoolean(30) : true,
    //         groups: [], // finalize
    //         nb_orders: 0,
    //         total_spent: 0,
    //     };
    // });

    let res = [
        {
            "id": 0,
            "first_name": "Ellie",
            "last_name": "Smitham",
            "email": "Ellie20@yahoo.com",
            "address": "963 Ivah Underpass",
            "zipcode": "68673-8262",
            "city": "Eloisehaven",
            "stateAbbr": "MO",
            "avatar": "https://marmelab.com/posters/avatar-0.jpeg",
            "birthday": "1976-04-07T19:52:51.957Z",
            "first_seen": "2022-11-25T10:03:05.745Z",
            "last_seen": "2023-08-03T19:03:07.315Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 1,
            "first_name": "Emma",
            "last_name": "Effertz",
            "email": "Emma.Effertz20@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-11-02T23:16:03.108Z",
            "last_seen": "2024-04-18T12:52:10.516Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 2,
            "first_name": "Chelsea",
            "last_name": "Stanton",
            "email": "Chelsea59@hotmail.com",
            "address": "4068 Sigmund Court",
            "zipcode": "69239",
            "city": "Osinskiside",
            "stateAbbr": "AL",
            "avatar": "https://marmelab.com/posters/avatar-1.jpeg",
            "birthday": "1984-10-22T21:32:46.083Z",
            "first_seen": "2022-12-06T17:15:44.593Z",
            "last_seen": "2024-02-18T08:54:29.021Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 3,
            "first_name": "Beryl",
            "last_name": "Koch",
            "email": "Beryl_Koch@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-03-15T07:00:33.053Z",
            "last_seen": "2024-06-03T04:25:57.057Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 4,
            "first_name": "Novella",
            "last_name": "Bruen",
            "email": "Novella_Bruen@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-11-19T22:02:16.122Z",
            "last_seen": "2023-10-18T22:44:31.656Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 5,
            "first_name": "Demario",
            "last_name": "Ward",
            "email": "Demario60@yahoo.com",
            "address": "54195 Fahey Islands",
            "zipcode": "22022-3172",
            "city": "Romainestad",
            "stateAbbr": "NV",
            "avatar": "https://marmelab.com/posters/avatar-2.jpeg",
            "birthday": "2003-07-01T14:43:31.471Z",
            "first_seen": "2024-03-03T20:21:27.315Z",
            "last_seen": "2024-06-01T22:41:04.917Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 6,
            "first_name": "Carissa",
            "last_name": "Hoppe",
            "email": "Carissa.Hoppe57@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-12-26T06:30:55.407Z",
            "last_seen": "2024-08-17T05:09:20.213Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 7,
            "first_name": "Ralph",
            "last_name": "Bartell",
            "email": "Ralph_Bartell@hotmail.com",
            "address": "200 Keeling Ramp",
            "zipcode": "76802-6152",
            "city": "North Alfordport",
            "stateAbbr": "SC",
            "avatar": "https://marmelab.com/posters/avatar-3.jpeg",
            "birthday": "1991-10-30T11:53:06.999Z",
            "first_seen": "2021-12-03T04:54:01.558Z",
            "last_seen": "2023-07-23T06:57:03.228Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 8,
            "first_name": "Stephany",
            "last_name": "Kertzmann",
            "email": "Stephany.Kertzmann@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-01-04T02:36:16.416Z",
            "last_seen": "2024-06-30T12:39:28.989Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 9,
            "first_name": "Howard",
            "last_name": "Jerde",
            "email": "Howard.Jerde@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-01-17T11:25:58.987Z",
            "last_seen": "2023-02-20T23:54:50.585Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 10,
            "first_name": "Otis",
            "last_name": "Rau",
            "email": "Otis_Rau@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-11-29T20:57:47.021Z",
            "last_seen": "2024-06-05T10:39:45.725Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 11,
            "first_name": "John",
            "last_name": "Schmeler",
            "email": "John23@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-10-19T22:14:33.703Z",
            "last_seen": "2024-08-10T00:24:09.956Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 12,
            "first_name": "Pietro",
            "last_name": "Quigley",
            "email": "Pietro.Quigley74@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-01-22T07:11:14.278Z",
            "last_seen": "2024-07-29T16:28:48.960Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 13,
            "first_name": "Mortimer",
            "last_name": "Oberbrunner",
            "email": "Mortimer.Oberbrunner@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-10-28T08:01:41.137Z",
            "last_seen": "2024-08-11T11:58:10.403Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 14,
            "first_name": "Cloyd",
            "last_name": "Crooks",
            "email": "Cloyd.Crooks@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-07-23T22:14:01.640Z",
            "last_seen": "2023-09-21T02:14:27.369Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 15,
            "first_name": "Kamren",
            "last_name": "Ebert",
            "email": "Kamren_Ebert56@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-09-04T01:16:49.567Z",
            "last_seen": "2023-01-19T03:53:19.738Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 16,
            "first_name": "Dee",
            "last_name": "Leannon",
            "email": "Dee_Leannon@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-11-09T01:04:47.558Z",
            "last_seen": "2024-07-18T03:17:30.326Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 17,
            "first_name": "Karlee",
            "last_name": "Kreiger",
            "email": "Karlee.Kreiger@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-06-13T19:39:59.510Z",
            "last_seen": "2024-05-15T12:03:13.889Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 18,
            "first_name": "Beverly",
            "last_name": "Raynor",
            "email": "Beverly_Raynor@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-11-03T14:45:18.016Z",
            "last_seen": "2024-06-20T08:20:04.506Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 19,
            "first_name": "Frances",
            "last_name": "Kozey",
            "email": "Frances.Kozey67@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-06-02T02:22:31.096Z",
            "last_seen": "2022-12-18T03:40:12.491Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 20,
            "first_name": "Edgardo",
            "last_name": "Hilll",
            "email": "Edgardo61@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-09-22T11:18:06.469Z",
            "last_seen": "2024-08-19T18:24:40.195Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 21,
            "first_name": "Pamela",
            "last_name": "Leuschke",
            "email": "Pamela19@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-07-06T12:51:05.000Z",
            "last_seen": "2024-08-10T14:34:59.453Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 22,
            "first_name": "Melany",
            "last_name": "Becker",
            "email": "Melany_Becker45@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-09-27T14:44:35.880Z",
            "last_seen": "2022-05-18T12:44:21.976Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 23,
            "first_name": "Ezekiel",
            "last_name": "Anderson",
            "email": "Ezekiel_Anderson43@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-02-13T15:26:47.589Z",
            "last_seen": "2024-08-26T09:30:50.347Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 24,
            "first_name": "Conrad",
            "last_name": "Walker",
            "email": "Conrad.Walker2@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-01-04T23:52:03.192Z",
            "last_seen": "2024-07-15T04:17:52.430Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 25,
            "first_name": "Lyric",
            "last_name": "Kunze",
            "email": "Lyric.Kunze74@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-09-06T00:28:56.019Z",
            "last_seen": "2024-08-06T06:35:01.823Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 26,
            "first_name": "Althea",
            "last_name": "Gaylord",
            "email": "Althea.Gaylord@hotmail.com",
            "address": "746 Rogelio Forest",
            "zipcode": "77187",
            "city": "Ronbury",
            "stateAbbr": "NV",
            "avatar": "https://marmelab.com/posters/avatar-4.jpeg",
            "birthday": "1974-01-30T19:53:52.810Z",
            "first_seen": "2020-12-19T13:43:46.235Z",
            "last_seen": "2023-02-26T08:30:07.224Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 27,
            "first_name": "Marlen",
            "last_name": "Morar",
            "email": "Marlen_Morar@gmail.com",
            "address": "692 Kuhn Ford",
            "zipcode": "47117-7304",
            "city": "Port Marielaburgh",
            "stateAbbr": "VA",
            "avatar": "https://marmelab.com/posters/avatar-5.jpeg",
            "birthday": "1994-06-02T17:53:50.079Z",
            "first_seen": "2021-01-20T22:31:26.820Z",
            "last_seen": "2024-03-02T21:52:01.550Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 28,
            "first_name": "Camilla",
            "last_name": "Kuhlman",
            "email": "Camilla.Kuhlman@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-01-25T11:11:07.866Z",
            "last_seen": "2024-02-20T14:53:19.744Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 29,
            "first_name": "Dortha",
            "last_name": "Thiel",
            "email": "Dortha.Thiel57@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-12-19T11:23:22.789Z",
            "last_seen": "2023-06-14T18:18:44.163Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 30,
            "first_name": "Griffin",
            "last_name": "Kessler",
            "email": "Griffin27@hotmail.com",
            "address": "05748 Lind Springs",
            "zipcode": "82682-5434",
            "city": "East Jarret",
            "stateAbbr": "NJ",
            "avatar": "https://marmelab.com/posters/avatar-6.jpeg",
            "birthday": "1987-05-01T23:32:42.866Z",
            "first_seen": "2023-12-04T09:31:41.614Z",
            "last_seen": "2024-05-08T02:24:31.876Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 31,
            "first_name": "Jonathan",
            "last_name": "Kertzmann",
            "email": "Jonathan_Kertzmann22@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-08-26T01:05:28.747Z",
            "last_seen": "2024-05-06T19:38:28.174Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 32,
            "first_name": "Moriah",
            "last_name": "Toy",
            "email": "Moriah57@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-04-23T17:10:39.822Z",
            "last_seen": "2024-04-24T03:49:45.110Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 33,
            "first_name": "Florencio",
            "last_name": "Mills",
            "email": "Florencio.Mills15@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-04-03T19:47:44.536Z",
            "last_seen": "2021-07-01T18:52:19.145Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 34,
            "first_name": "Dandre",
            "last_name": "Tremblay",
            "email": "Dandre50@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-01-16T14:29:31.508Z",
            "last_seen": "2024-06-04T19:50:35.932Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 35,
            "first_name": "Yasmeen",
            "last_name": "Russel",
            "email": "Yasmeen21@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-09-17T19:42:33.601Z",
            "last_seen": "2024-05-20T02:13:09.563Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 36,
            "first_name": "Susanna",
            "last_name": "Bradtke",
            "email": "Susanna39@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-03-12T11:56:12.736Z",
            "last_seen": "2024-07-06T21:20:36.281Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 37,
            "first_name": "Greg",
            "last_name": "Kassulke",
            "email": "Greg6@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-03-24T22:50:45.749Z",
            "last_seen": "2024-03-12T00:08:26.056Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 38,
            "first_name": "Alfonzo",
            "last_name": "Bernhard",
            "email": "Alfonzo_Bernhard@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-04-12T09:13:05.958Z",
            "last_seen": "2024-06-13T14:27:05.118Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 39,
            "first_name": "Ricardo",
            "last_name": "Reinger",
            "email": "Ricardo.Reinger78@hotmail.com",
            "address": "9784 Hansen Burgs",
            "zipcode": "31346",
            "city": "East Marielle",
            "stateAbbr": "CA",
            "avatar": "https://marmelab.com/posters/avatar-7.jpeg",
            "birthday": "1988-09-25T15:10:44.876Z",
            "first_seen": "2022-08-31T17:02:02.788Z",
            "last_seen": "2024-08-26T16:04:21.010Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 40,
            "first_name": "Jaeden",
            "last_name": "Gorczany",
            "email": "Jaeden.Gorczany91@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-03-06T01:15:20.259Z",
            "last_seen": "2024-07-18T09:43:37.104Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 41,
            "first_name": "Max",
            "last_name": "Brakus",
            "email": "Max.Brakus@hotmail.com",
            "address": "75488 Watsica Place",
            "zipcode": "04214",
            "city": "Starkville",
            "stateAbbr": "DE",
            "avatar": "https://marmelab.com/posters/avatar-8.jpeg",
            "birthday": "1966-07-29T15:28:06.037Z",
            "first_seen": "2024-06-17T21:33:30.219Z",
            "last_seen": "2024-07-07T04:06:11.655Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 42,
            "first_name": "Kiana",
            "last_name": "Larkin",
            "email": "Kiana_Larkin61@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-10-23T06:07:10.538Z",
            "last_seen": "2023-03-20T12:32:55.900Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 43,
            "first_name": "Kory",
            "last_name": "Pfeffer",
            "email": "Kory_Pfeffer51@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-11-14T10:14:01.663Z",
            "last_seen": "2023-02-16T11:47:37.874Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 44,
            "first_name": "Evan",
            "last_name": "Stark",
            "email": "Evan76@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-08-09T16:01:36.401Z",
            "last_seen": "2024-08-17T01:40:15.224Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 45,
            "first_name": "Nayeli",
            "last_name": "Schuppe",
            "email": "Nayeli18@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-03-24T16:56:46.090Z",
            "last_seen": "2023-12-24T15:33:03.408Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 46,
            "first_name": "Lisa",
            "last_name": "Cummings",
            "email": "Lisa.Cummings38@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-08-30T13:57:06.067Z",
            "last_seen": "2023-06-25T10:08:47.194Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 47,
            "first_name": "Gabe",
            "last_name": "Swift",
            "email": "Gabe_Swift45@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-05-17T22:33:15.758Z",
            "last_seen": "2023-12-23T01:05:38.884Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 48,
            "first_name": "Odessa",
            "last_name": "Abshire",
            "email": "Odessa.Abshire@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-12-23T23:08:34.747Z",
            "last_seen": "2024-05-29T04:11:08.895Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 49,
            "first_name": "Danyka",
            "last_name": "Kris",
            "email": "Danyka.Kris@yahoo.com",
            "address": "1811 Savanna Mount",
            "zipcode": "38108-3994",
            "city": "South Vernie",
            "stateAbbr": "MT",
            "avatar": "https://marmelab.com/posters/avatar-9.jpeg",
            "birthday": "1983-08-09T04:14:43.995Z",
            "first_seen": "2022-06-28T01:27:31.089Z",
            "last_seen": "2024-04-12T22:06:10.642Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 50,
            "first_name": "Khalid",
            "last_name": "Reilly",
            "email": "Khalid28@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-10-08T20:01:08.844Z",
            "last_seen": "2024-06-29T20:59:44.326Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 51,
            "first_name": "Lia",
            "last_name": "Wisoky",
            "email": "Lia73@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-05-26T13:22:36.623Z",
            "last_seen": "2024-04-26T22:20:56.753Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 52,
            "first_name": "Aliyah",
            "last_name": "Kessler",
            "email": "Aliyah_Kessler@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-11-10T01:39:28.893Z",
            "last_seen": "2024-06-01T06:45:44.662Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 53,
            "first_name": "Bethany",
            "last_name": "Treutel",
            "email": "Bethany_Treutel@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-05-17T15:03:29.320Z",
            "last_seen": "2021-08-07T23:40:29.506Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 54,
            "first_name": "Randi",
            "last_name": "Price",
            "email": "Randi.Price60@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-10-31T00:58:53.954Z",
            "last_seen": "2023-10-10T16:49:17.154Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 55,
            "first_name": "Shanny",
            "last_name": "Padberg",
            "email": "Shanny_Padberg87@gmail.com",
            "address": "0362 Jakubowski Mill",
            "zipcode": "26545-4115",
            "city": "Alvahton",
            "stateAbbr": "MO",
            "avatar": "https://marmelab.com/posters/avatar-10.jpeg",
            "birthday": "1990-02-22T20:14:19.736Z",
            "first_seen": "2021-06-20T12:10:05.866Z",
            "last_seen": "2024-02-04T05:15:34.369Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 56,
            "first_name": "Faustino",
            "last_name": "Howell",
            "email": "Faustino.Howell@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-10-31T22:01:17.251Z",
            "last_seen": "2024-08-31T12:35:45.156Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 57,
            "first_name": "Daphney",
            "last_name": "Schowalter",
            "email": "Daphney.Schowalter@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-06-29T19:19:27.004Z",
            "last_seen": "2024-08-09T08:11:31.363Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 58,
            "first_name": "Gabriella",
            "last_name": "Schneider",
            "email": "Gabriella.Schneider99@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-02-25T10:03:16.802Z",
            "last_seen": "2022-06-03T15:31:58.145Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 59,
            "first_name": "Gregorio",
            "last_name": "Grimes",
            "email": "Gregorio27@gmail.com",
            "address": "41446 Sauer Falls",
            "zipcode": "27597",
            "city": "Greentown",
            "stateAbbr": "WA",
            "avatar": "https://marmelab.com/posters/avatar-11.jpeg",
            "birthday": "2017-04-16T15:57:31.439Z",
            "first_seen": "2022-10-26T02:36:30.610Z",
            "last_seen": "2023-11-09T01:18:01.065Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 60,
            "first_name": "Meaghan",
            "last_name": "Cassin",
            "email": "Meaghan89@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-06-11T04:25:02.850Z",
            "last_seen": "2024-05-19T09:08:17.933Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 61,
            "first_name": "Etha",
            "last_name": "VonRueden",
            "email": "Etha_VonRueden@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-11-16T05:21:43.259Z",
            "last_seen": "2024-07-05T03:02:40.655Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 62,
            "first_name": "Lilian",
            "last_name": "Labadie",
            "email": "Lilian.Labadie27@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-05-10T06:35:43.168Z",
            "last_seen": "2023-07-02T11:28:06.474Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 63,
            "first_name": "Michale",
            "last_name": "Kunde",
            "email": "Michale.Kunde@yahoo.com",
            "address": "4062 Olson Parkway",
            "zipcode": "68250-5461",
            "city": "East Delphia",
            "stateAbbr": "FL",
            "avatar": "https://marmelab.com/posters/avatar-12.jpeg",
            "birthday": "2015-03-30T22:40:24.448Z",
            "first_seen": "2023-05-09T13:31:26.082Z",
            "last_seen": "2024-07-09T10:59:58.377Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 64,
            "first_name": "Sarai",
            "last_name": "Rempel",
            "email": "Sarai_Rempel@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-11-05T20:17:18.763Z",
            "last_seen": "2024-04-10T18:21:22.061Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 65,
            "first_name": "Chester",
            "last_name": "Douglas",
            "email": "Chester81@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-04-22T06:21:22.974Z",
            "last_seen": "2024-08-04T02:18:17.759Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 66,
            "first_name": "Sarah",
            "last_name": "Bernier",
            "email": "Sarah3@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-07-31T22:43:51.594Z",
            "last_seen": "2024-08-27T04:32:58.471Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 67,
            "first_name": "Cara",
            "last_name": "Fisher",
            "email": "Cara.Fisher16@hotmail.com",
            "address": "75626 Jacquelyn Stream",
            "zipcode": "33418-6030",
            "city": "Alvenamouth",
            "stateAbbr": "MN",
            "avatar": "https://marmelab.com/posters/avatar-13.jpeg",
            "birthday": "1989-07-20T23:03:33.830Z",
            "first_seen": "2024-03-26T10:51:45.551Z",
            "last_seen": "2024-06-16T19:01:07.590Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 68,
            "first_name": "Jakayla",
            "last_name": "Kling",
            "email": "Jakayla2@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-05-31T10:33:35.693Z",
            "last_seen": "2024-06-04T15:54:51.929Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 69,
            "first_name": "Selmer",
            "last_name": "Herman",
            "email": "Selmer25@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-02-19T18:01:14.334Z",
            "last_seen": "2024-06-05T13:13:22.549Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 70,
            "first_name": "Jane",
            "last_name": "Boyer",
            "email": "Jane17@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-05-20T07:44:11.746Z",
            "last_seen": "2024-05-07T05:34:47.421Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 71,
            "first_name": "Elda",
            "last_name": "Ward",
            "email": "Elda_Ward5@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-08-14T13:13:09.199Z",
            "last_seen": "2024-08-30T16:41:00.836Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 72,
            "first_name": "Diamond",
            "last_name": "Balistreri",
            "email": "Diamond_Balistreri31@gmail.com",
            "address": "6495 Mertz Streets",
            "zipcode": "49373-5083",
            "city": "Port Haileyville",
            "stateAbbr": "TN",
            "avatar": "https://marmelab.com/posters/avatar-14.jpeg",
            "birthday": "1995-04-17T01:18:06.355Z",
            "first_seen": "2023-01-06T00:42:41.593Z",
            "last_seen": "2023-11-15T05:11:29.463Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 73,
            "first_name": "Neil",
            "last_name": "Spinka",
            "email": "Neil_Spinka@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-05-01T06:05:35.614Z",
            "last_seen": "2024-06-24T00:36:06.492Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 74,
            "first_name": "Percival",
            "last_name": "Brakus",
            "email": "Percival.Brakus13@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-12-02T06:54:33.950Z",
            "last_seen": "2024-08-25T17:56:52.218Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 75,
            "first_name": "Dovie",
            "last_name": "Schamberger",
            "email": "Dovie17@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-07-06T21:39:06.403Z",
            "last_seen": "2024-01-08T07:15:14.603Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 76,
            "first_name": "Miles",
            "last_name": "Kunze",
            "email": "Miles46@yahoo.com",
            "address": "342 Juvenal Roads",
            "zipcode": "77272",
            "city": "New Christop",
            "stateAbbr": "LA",
            "avatar": "https://marmelab.com/posters/avatar-15.jpeg",
            "birthday": "1996-02-04T11:04:08.696Z",
            "first_seen": "2022-07-12T21:11:11.008Z",
            "last_seen": "2024-05-14T07:50:16.920Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 77,
            "first_name": "Gregorio",
            "last_name": "Greenholt",
            "email": "Gregorio79@gmail.com",
            "address": "182 Elise Courts",
            "zipcode": "17619",
            "city": "Vivastad",
            "stateAbbr": "AL",
            "avatar": "https://marmelab.com/posters/avatar-16.jpeg",
            "birthday": "1996-10-13T23:03:40.884Z",
            "first_seen": "2020-08-17T05:41:07.471Z",
            "last_seen": "2023-08-30T00:34:00.121Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 78,
            "first_name": "Maybell",
            "last_name": "Veum",
            "email": "Maybell_Veum@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-05-07T15:59:22.371Z",
            "last_seen": "2024-07-16T02:04:41.262Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 79,
            "first_name": "Laney",
            "last_name": "Barrows",
            "email": "Laney.Barrows21@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-05-28T10:05:33.981Z",
            "last_seen": "2024-06-28T17:26:16.411Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 80,
            "first_name": "Antwan",
            "last_name": "Hackett",
            "email": "Antwan34@hotmail.com",
            "address": "82212 Krystel Prairie",
            "zipcode": "92077",
            "city": "North Nicole",
            "stateAbbr": "NY",
            "avatar": "https://marmelab.com/posters/avatar-17.jpeg",
            "birthday": "1985-08-14T04:12:01.881Z",
            "first_seen": "2024-02-18T16:11:22.724Z",
            "last_seen": "2024-07-17T19:59:59.847Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 81,
            "first_name": "Norval",
            "last_name": "Wolff",
            "email": "Norval99@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-09-05T06:39:23.927Z",
            "last_seen": "2024-03-13T14:55:23.192Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 82,
            "first_name": "Ana",
            "last_name": "Keebler",
            "email": "Ana95@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-06-17T01:28:48.820Z",
            "last_seen": "2023-07-26T05:33:08.949Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 83,
            "first_name": "Alexandro",
            "last_name": "Williamson",
            "email": "Alexandro24@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2020-10-04T08:28:11.164Z",
            "last_seen": "2023-06-10T22:36:00.964Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 84,
            "first_name": "Blair",
            "last_name": "Schmidt",
            "email": "Blair.Schmidt@yahoo.com",
            "address": "3988 Reba Causeway",
            "zipcode": "76255-0448",
            "city": "North Monroe",
            "stateAbbr": "NJ",
            "avatar": "https://marmelab.com/posters/avatar-18.jpeg",
            "birthday": "1989-11-06T12:28:01.834Z",
            "first_seen": "2022-03-29T07:31:15.464Z",
            "last_seen": "2023-04-18T02:27:44.797Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 85,
            "first_name": "Jairo",
            "last_name": "Rodriguez",
            "email": "Jairo55@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2021-12-30T18:56:28.907Z",
            "last_seen": "2024-08-21T08:57:01.544Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 86,
            "first_name": "Amber",
            "last_name": "Douglas",
            "email": "Amber.Douglas@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-07-01T13:05:52.532Z",
            "last_seen": "2024-08-25T15:30:52.387Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 87,
            "first_name": "Orlando",
            "last_name": "Purdy",
            "email": "Orlando62@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-10-14T23:02:12.848Z",
            "last_seen": "2024-07-19T16:24:11.644Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 88,
            "first_name": "Sabrina",
            "last_name": "Ritchie",
            "email": "Sabrina_Ritchie18@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-06-14T22:17:24.860Z",
            "last_seen": "2024-08-14T19:37:47.373Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 89,
            "first_name": "Price",
            "last_name": "Streich",
            "email": "Price73@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-09-10T21:39:24.468Z",
            "last_seen": "2024-06-11T21:00:32.813Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 90,
            "first_name": "Alyce",
            "last_name": "Kuhic",
            "email": "Alyce.Kuhic@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-07-16T22:53:58.879Z",
            "last_seen": "2024-08-27T18:04:02.366Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 91,
            "first_name": "Alessandra",
            "last_name": "Beahan",
            "email": "Alessandra40@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-08-23T17:25:22.799Z",
            "last_seen": "2024-05-11T19:44:31.537Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 92,
            "first_name": "Kailee",
            "last_name": "Funk",
            "email": "Kailee.Funk21@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-06-21T15:33:14.768Z",
            "last_seen": "2024-08-15T12:57:54.437Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 93,
            "first_name": "Maegan",
            "last_name": "Fritsch",
            "email": "Maegan_Fritsch63@gmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-01-12T07:16:31.512Z",
            "last_seen": "2024-06-08T22:24:37.056Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 94,
            "first_name": "Ben",
            "last_name": "Skiles",
            "email": "Ben_Skiles@gmail.com",
            "address": "6600 Arjun Gateway",
            "zipcode": "59313-5219",
            "city": "North Cecelia",
            "stateAbbr": "UT",
            "avatar": "https://marmelab.com/posters/avatar-19.jpeg",
            "birthday": "1973-05-22T04:08:50.024Z",
            "first_seen": "2021-11-14T11:16:05.994Z",
            "last_seen": "2023-09-23T13:36:34.576Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": false,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 95,
            "first_name": "Korey",
            "last_name": "Ullrich",
            "email": "Korey70@hotmail.com",
            "address": "202 Olin Springs",
            "zipcode": "85682-6398",
            "city": "Bartellchester",
            "stateAbbr": "RI",
            "avatar": "https://marmelab.com/posters/avatar-20.jpeg",
            "birthday": "2017-06-02T03:24:07.315Z",
            "first_seen": "2023-12-05T21:26:13.875Z",
            "last_seen": "2024-08-10T18:12:15.371Z",
            "has_ordered": true,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 96,
            "first_name": "Orion",
            "last_name": "MacGyver",
            "email": "Orion52@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-12-29T12:30:27.370Z",
            "last_seen": "2024-08-31T06:14:08.561Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 97,
            "first_name": "Kassandra",
            "last_name": "Strosin",
            "email": "Kassandra64@yahoo.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2024-06-05T00:49:10.916Z",
            "last_seen": "2024-07-24T20:04:10.964Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 98,
            "first_name": "Tom",
            "last_name": "Stokes",
            "email": "Tom.Stokes@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2023-09-03T15:19:52.882Z",
            "last_seen": "2024-07-27T20:03:45.553Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
        {
            "id": 99,
            "first_name": "Lupe",
            "last_name": "Howe",
            "email": "Lupe.Howe@hotmail.com",
            "address": null,
            "zipcode": null,
            "city": null,
            "stateAbbr": null,
            "birthday": null,
            "first_seen": "2022-12-30T06:30:23.564Z",
            "last_seen": "2024-08-03T14:01:01.250Z",
            "has_ordered": false,
            "latest_purchase": null,
            "has_newsletter": true,
            "groups": [],
            "nb_orders": 0,
            "total_spent": 0
        },
    ];


    return res;
};

export type Customer = {
    id: number;
    first_name: string;
    last_name: string;
    email: string;
    address: string | null;
    zipcode: string | null;
    city: string | null;
    stateAbbr: string | null;
    avatar?: string;
    birthday: string | null;
    first_seen: string;
    last_seen: string;
    has_ordered: boolean;
    latest_purchase: string | null;
    has_newsletter: boolean;
    groups: string[];
    nb_orders: number;
    total_spent: number;
};
