import { random, lorem } from 'faker/locale/en';

import { randomFloat, weightedBoolean } from './utils';
import type { Db } from './types';

const productReferences = {
    animals: [
        'Cat Nose',
        'Dog Grass',
        'Brown Cow',
        'Leopard Road',
        'Sad Dog',
        'Pelican Pier',
        'Green Birds',
        'Concrete Seaguls',
        'Hiding Seagul',
        'Sand Caravan',
    ],
    beard: [
        'Black Auburn',
        'Basket Beard',
        'Handlebar Moustache',
        'White Beard',
        'Sailor Man',
        'Natural Beard',
        'Yeard Phone',
        'Braid Beard',
        'Terminal Black',
        'Short Boxed',
    ],
    business: [
        'Corporate Prop',
        'Office Chairs',
        'White Clock',
        'Work Suit',
        'Suit & Tie',
        'Shake Hands',
        'Building Sky',
        'Yellow Pad',
        'Work Devices',
        'Hands Clap',
        'Work Meeting',
    ],
    cars: [
        'Old Combi',
        'Asian Plates',
        'Pedestrian Crossing',
        'Farmer Boy',
        'Make Over',
        'Sports Sunset',
        'Desert Jeep',
        'Highway Bridge',
        'Race Stickers',
        'White Deluxe',
    ],
    city: [
        'Bridge Lights',
        'Color Dots',
        'Cloud Suspension',
        'Paved Street',
        'Blue Bay',
        'Wooden Door',
        'Concrete Angles',
        'London Lights',
        'Fort Point',
        'Rainy Glass',
    ],
    flowers: [
        'Apricot Tree',
        'Orange Rose',
        'Purple Petunia',
        'Water Lily',
        'White Peony',
        'Poppy Field',
        'Blue Flax',
        'Love Roses',
        'California Poppy',
        'Dalhia Colors',
    ],
    food: [
        'Fuzzy Forks',
        'Stamp Mug',
        'Two Expressos',
        'Red Latte',
        'Black Grapes',
        'Forgotten Strawberries',
        'Close Steam',
        'Brewing Tea',
        'Red Onions',
        'Dark Honey',
    ],
    nature: [
        'Distant Mountains',
        'Fog Pond',
        'Sand Rocks',
        'Pebble Shore',
        'Eroded Fractals',
        'Water Fall',
        'Drif Wood',
        'Dirt Track',
        'Green Grass',
        'Yellow Lichen',
    ],
    people: [
        'Crossing Alone',
        'Budding Grove',
        'Light Hair',
        'Black & White',
        'Rock Concert',
        'Meeting Bench',
        'Son & Lumière',
        'Running Boy',
        'Dining Hall',
        'Tunnel People',
    ],
    sports: [
        'Feather Ball',
        'Wall Skate',
        'Kick Flip',
        'Down Hill',
        'Baseball Night',
        'Touch Line',
        'Alone Jogger',
        'Green Basket',
        'Mud Hug',
        'Metal Cycle',
    ],
    tech: [
        'Black Screen',
        'Phone Call',
        'Tablet & Phone',
        'No Battery',
        'Phone Book',
        'Camera Parts',
        'Fuzzy Phone',
        'Music & Light',
        'Eye Rest',
        'Aligned Parts',
    ],
    travel: [
        'Distant Jet',
        'Foggy Beach',
        'White Lime',
        'Mysterious Cloud',
        'Mountain Top',
        'Light House',
        'Gray Day',
        'Desert Walkway',
        'Train Track',
        'Plane Trees',
    ],
    water: [
        'Fresh Stream',
        'Reed Line',
        'Mud Tracks',
        'Beach Gazebo',
        'Calm Sea',
        'Early Bath',
        'Aerial Coast',
        'Canal Street',
        'Artificial Beach',
        'Rainy Day',
    ],
};

export const generateProducts = (db: Db): Product[] => {
    let id = 0;

    // let result = db.categories.reduce(
    //     (acc, category) => [
    //         ...acc,
    //         ...Array.from(Array(10).keys()).map(index => {
    //             const width = randomFloat(10, 40);
    //             const height = randomFloat(10, 40);
    //
    //             return {
    //                 id: id++,
    //                 category_id: category.id,
    //                 reference: productReferences[category.name][index],
    //                 width: width,
    //                 height: height,
    //                 price: randomFloat(
    //                     (width * height) / 20,
    //                     (width * height) / 15
    //                 ),
    //                 thumbnail:
    //                     'https://marmelab.com/posters/' +
    //                     category.name +
    //                     '-' +
    //                     (index + 1) +
    //                     '.jpeg',
    //                 image:
    //                     'https://marmelab.com/posters/' +
    //                     category.name +
    //                     '-' +
    //                     (index + 1) +
    //                     '.jpeg',
    //                 description: lorem.paragraph(),
    //                 stock: weightedBoolean(10)
    //                     ? 0
    //                     : random.number({ min: 0, max: 150 }),
    //                 sales: 0,
    //             };
    //         }),
    //     ],
    //     []
    // );

    let result = [
        {
            "id": 0,
            "category_id": 0,
            "reference": "Cat Nose",
            "width": 27.6,
            "height": 30.88,
            "price": 42.86,
            "thumbnail": "https://marmelab.com/posters/animals-1.jpeg",
            "image": "https://marmelab.com/posters/animals-1.jpeg",
            "description": "Delectus et omnis earum quos consequuntur ad rerum. Magni alias eius earum rerum natus dolorem. Unde fugiat a rerum commodi totam molestiae aliquam sit.",
            "stock": 51,
            "sales": 30
        },
        {
            "id": 1,
            "category_id": 0,
            "reference": "Dog Grass",
            "width": 12.29,
            "height": 31.21,
            "price": 25.27,
            "thumbnail": "https://marmelab.com/posters/animals-2.jpeg",
            "image": "https://marmelab.com/posters/animals-2.jpeg",
            "description": "Velit laboriosam et amet. Neque molestias maxime itaque tenetur nihil et aspernatur ut rerum. Amet voluptas iste eaque adipisci laboriosam eum aut. Vero cupiditate dolorem molestiae debitis ut sint facere blanditiis ut. Nam ratione ut tenetur recusandae quis ratione modi. Iusto est quam odit amet eum voluptas non dolor.",
            "stock": 15,
            "sales": 27
        },
        {
            "id": 2,
            "category_id": 0,
            "reference": "Brown Cow",
            "width": 33.49,
            "height": 13.94,
            "price": 30.44,
            "thumbnail": "https://marmelab.com/posters/animals-3.jpeg",
            "image": "https://marmelab.com/posters/animals-3.jpeg",
            "description": "Aut et nostrum neque doloribus. Corrupti voluptatem sed modi ut eos harum. Nobis repellat quos et est. Voluptatem officiis eos nihil earum id.",
            "stock": 144,
            "sales": 16
        },
        {
            "id": 3,
            "category_id": 0,
            "reference": "Leopard Road",
            "width": 18.24,
            "height": 25.71,
            "price": 29.79,
            "thumbnail": "https://marmelab.com/posters/animals-4.jpeg",
            "image": "https://marmelab.com/posters/animals-4.jpeg",
            "description": "Vitae necessitatibus ut laboriosam dolores qui recusandae. Modi esse molestiae a omnis veniam numquam non sed illum. Doloremque minus consectetur laboriosam nihil.",
            "stock": 133,
            "sales": 20
        },
        {
            "id": 4,
            "category_id": 0,
            "reference": "Sad Dog",
            "width": 17.96,
            "height": 15.91,
            "price": 18.08,
            "thumbnail": "https://marmelab.com/posters/animals-5.jpeg",
            "image": "https://marmelab.com/posters/animals-5.jpeg",
            "description": "Ipsam et et optio omnis recusandae et in laudantium. Et ad nihil est. Id laboriosam nihil voluptas. Quas corporis officiis vero laboriosam esse eveniet veritatis aut.",
            "stock": 89,
            "sales": 15
        },
        {
            "id": 5,
            "category_id": 0,
            "reference": "Pelican Pier",
            "width": 19.1,
            "height": 28.15,
            "price": 29.27,
            "thumbnail": "https://marmelab.com/posters/animals-6.jpeg",
            "image": "https://marmelab.com/posters/animals-6.jpeg",
            "description": "Totam qui vel. Quia rerum consequatur vel at. Quia est voluptatum reprehenderit.",
            "stock": 78,
            "sales": 40
        },
        {
            "id": 6,
            "category_id": 0,
            "reference": "Green Birds",
            "width": 29.74,
            "height": 32.81,
            "price": 57.63,
            "thumbnail": "https://marmelab.com/posters/animals-7.jpeg",
            "image": "https://marmelab.com/posters/animals-7.jpeg",
            "description": "Repudiandae nulla voluptates nam voluptas quidem libero a voluptatibus ex. Laborum fuga voluptatibus quia omnis a deleniti ducimus. Fuga sequi modi facilis dicta sed. Et eos tenetur nulla. Est id expedita eveniet.",
            "stock": 22,
            "sales": 20
        },
        {
            "id": 7,
            "category_id": 0,
            "reference": "Concrete Seaguls",
            "width": 18.53,
            "height": 21.7,
            "price": 25.62,
            "thumbnail": "https://marmelab.com/posters/animals-8.jpeg",
            "image": "https://marmelab.com/posters/animals-8.jpeg",
            "description": "Error reprehenderit dolores. Dignissimos corporis nisi odit repellendus aliquid laudantium. Omnis ab placeat sequi. Occaecati animi provident delectus quia.",
            "stock": 90,
            "sales": 19
        },
        {
            "id": 8,
            "category_id": 0,
            "reference": "Hiding Seagul",
            "width": 31.97,
            "height": 37.6,
            "price": 74.09,
            "thumbnail": "https://marmelab.com/posters/animals-9.jpeg",
            "image": "https://marmelab.com/posters/animals-9.jpeg",
            "description": "Rem aut repellendus odit. Illo mollitia minus ducimus ut id deserunt dolor quo cupiditate. Impedit maxime explicabo vel quod facere rerum quod dolor est. Odit exercitationem laborum ut sequi nostrum aut. Qui fugiat dicta et. Aut nobis natus molestiae perferendis voluptatem quo officia est non.",
            "stock": 24,
            "sales": 23
        },
        {
            "id": 9,
            "category_id": 0,
            "reference": "Sand Caravan",
            "width": 32.62,
            "height": 17.18,
            "price": 34.27,
            "thumbnail": "https://marmelab.com/posters/animals-10.jpeg",
            "image": "https://marmelab.com/posters/animals-10.jpeg",
            "description": "Odio facilis beatae. Rerum deleniti quos provident voluptatum. Aut quo vel. Sit non adipisci aliquam.",
            "stock": 87,
            "sales": 11
        },
        {
            "id": 10,
            "category_id": 1,
            "reference": "Black Auburn",
            "width": 27.6,
            "height": 12.14,
            "price": 21.83,
            "thumbnail": "https://marmelab.com/posters/beard-1.jpeg",
            "image": "https://marmelab.com/posters/beard-1.jpeg",
            "description": "Excepturi doloremque dolores in laudantium quasi voluptatem. Iste et molestiae quo distinctio. Recusandae enim veritatis nam aliquid cumque cum enim totam quas.",
            "stock": 145,
            "sales": 14
        },
        {
            "id": 11,
            "category_id": 1,
            "reference": "Basket Beard",
            "width": 29.88,
            "height": 26.67,
            "price": 52.19,
            "thumbnail": "https://marmelab.com/posters/beard-2.jpeg",
            "image": "https://marmelab.com/posters/beard-2.jpeg",
            "description": "Qui autem deserunt. Officiis accusamus corporis ullam ducimus et. Et et minima sint in maxime aut facilis. Voluptas odit qui doloribus cumque molestiae nam. Incidunt excepturi quam et rerum sint aut.",
            "stock": 30,
            "sales": 21
        },
        {
            "id": 12,
            "category_id": 1,
            "reference": "Handlebar Moustache",
            "width": 24.8,
            "height": 34.15,
            "price": 48.47,
            "thumbnail": "https://marmelab.com/posters/beard-3.jpeg",
            "image": "https://marmelab.com/posters/beard-3.jpeg",
            "description": "Dolor sunt voluptatem molestiae. Ipsa laboriosam eveniet aspernatur cum et alias laborum. Aliquam quidem quod dolorem et eligendi et. Est doloribus est tenetur et quibusdam.",
            "stock": 100,
            "sales": 17
        },
        {
            "id": 13,
            "category_id": 1,
            "reference": "White Beard",
            "width": 22.88,
            "height": 19.71,
            "price": 29.22,
            "thumbnail": "https://marmelab.com/posters/beard-4.jpeg",
            "image": "https://marmelab.com/posters/beard-4.jpeg",
            "description": "Ab neque consectetur quas vitae. Saepe alias sed eos cupiditate qui corporis ut. Nam omnis eaque quis ab ut aut enim ut. Quae mollitia porro ut vitae dignissimos qui quos. Id ad voluptatem qui eligendi blanditiis libero. Aut maiores voluptatem.",
            "stock": 112,
            "sales": 13
        },
        {
            "id": 14,
            "category_id": 1,
            "reference": "Sailor Man",
            "width": 36.94,
            "height": 22.02,
            "price": 45.69,
            "thumbnail": "https://marmelab.com/posters/beard-5.jpeg",
            "image": "https://marmelab.com/posters/beard-5.jpeg",
            "description": "Voluptates magni consequatur aliquid nobis accusamus nam molestiae suscipit. Doloremque id aperiam eligendi qui ratione. Ea possimus excepturi provident.",
            "stock": 14,
            "sales": 16
        },
        {
            "id": 15,
            "category_id": 1,
            "reference": "Natural Beard",
            "width": 16.39,
            "height": 31.69,
            "price": 34.18,
            "thumbnail": "https://marmelab.com/posters/beard-6.jpeg",
            "image": "https://marmelab.com/posters/beard-6.jpeg",
            "description": "Tenetur id est blanditiis quod sit magni optio recusandae et. Quaerat aliquam magnam sed ratione qui tempora ut voluptatem. Minima inventore nisi placeat. Adipisci consequuntur accusantium ea ab quia temporibus quae. Occaecati eveniet asperiores similique quaerat asperiores repudiandae. Impedit voluptates odio non.",
            "stock": 0,
            "sales": 27
        },
        {
            "id": 16,
            "category_id": 1,
            "reference": "Yeard Phone",
            "width": 34.54,
            "height": 14.14,
            "price": 26.11,
            "thumbnail": "https://marmelab.com/posters/beard-7.jpeg",
            "image": "https://marmelab.com/posters/beard-7.jpeg",
            "description": "Eligendi expedita modi praesentium laboriosam quam laudantium facilis molestiae reprehenderit. Amet qui ipsum aliquid aut dolorum et sit quod recusandae. Ut inventore ut illo reiciendis adipisci praesentium voluptatem.",
            "stock": 143,
            "sales": 12
        },
        {
            "id": 17,
            "category_id": 1,
            "reference": "Braid Beard",
            "width": 14.58,
            "height": 27.23,
            "price": 24.54,
            "thumbnail": "https://marmelab.com/posters/beard-8.jpeg",
            "image": "https://marmelab.com/posters/beard-8.jpeg",
            "description": "Minus ex neque vel laudantium nobis accusantium. Autem et sit dolores ullam magnam. Voluptatem aut eos cupiditate reprehenderit velit. Voluptate incidunt quas eos aut sint.",
            "stock": 78,
            "sales": 32
        },
        {
            "id": 18,
            "category_id": 1,
            "reference": "Terminal Black",
            "width": 12.46,
            "height": 29.18,
            "price": 23.65,
            "thumbnail": "https://marmelab.com/posters/beard-9.jpeg",
            "image": "https://marmelab.com/posters/beard-9.jpeg",
            "description": "Explicabo modi non molestias facilis qui sint est minus mollitia. Culpa quod eius. Vel quaerat culpa debitis rerum consequuntur earum explicabo. Repudiandae natus earum ducimus nesciunt sint. Hic temporibus nam dolorum veritatis possimus.",
            "stock": 123,
            "sales": 48
        },
        {
            "id": 19,
            "category_id": 1,
            "reference": "Short Boxed",
            "width": 38.62,
            "height": 22.28,
            "price": 56.82,
            "thumbnail": "https://marmelab.com/posters/beard-10.jpeg",
            "image": "https://marmelab.com/posters/beard-10.jpeg",
            "description": "Asperiores illum perferendis magnam quis recusandae aut quia dolor sed. Fugit unde omnis a corporis. Eius est vero tempore tempora velit dolore qui neque eius. Reiciendis vel aut ad esse velit. Voluptate est autem ut maiores sed quaerat porro quia. Officiis nostrum reiciendis ut.",
            "stock": 48,
            "sales": 24
        },
        {
            "id": 20,
            "category_id": 2,
            "reference": "Corporate Prop",
            "width": 17.06,
            "height": 11.59,
            "price": 11.5,
            "thumbnail": "https://marmelab.com/posters/business-1.jpeg",
            "image": "https://marmelab.com/posters/business-1.jpeg",
            "description": "Eveniet ipsam voluptatibus. Maxime modi eius. Dolorem saepe est voluptatem eos omnis sed dolorem.",
            "stock": 48,
            "sales": 12
        },
        {
            "id": 21,
            "category_id": 2,
            "reference": "Office Chairs",
            "width": 29.57,
            "height": 12.81,
            "price": 22.39,
            "thumbnail": "https://marmelab.com/posters/business-2.jpeg",
            "image": "https://marmelab.com/posters/business-2.jpeg",
            "description": "Voluptas at quisquam quasi vel. Libero facere qui veritatis perferendis rerum corrupti et ipsam. Quam quia eum quo enim voluptatem est accusamus voluptatem. Architecto magni dolores non maiores.",
            "stock": 14,
            "sales": 19
        },
        {
            "id": 22,
            "category_id": 2,
            "reference": "White Clock",
            "width": 17.76,
            "height": 12.03,
            "price": 13.94,
            "thumbnail": "https://marmelab.com/posters/business-3.jpeg",
            "image": "https://marmelab.com/posters/business-3.jpeg",
            "description": "Ea eum omnis atque recusandae perspiciatis. Commodi cum aut sunt odio. Non ut quo. Nihil qui illum.",
            "stock": 148,
            "sales": 33
        },
        {
            "id": 23,
            "category_id": 2,
            "reference": "Work Suit",
            "width": 17.97,
            "height": 35.09,
            "price": 33.82,
            "thumbnail": "https://marmelab.com/posters/business-4.jpeg",
            "image": "https://marmelab.com/posters/business-4.jpeg",
            "description": "Animi laboriosam aut magnam error. Libero voluptatibus in numquam fugit impedit explicabo rerum. Et inventore at quia sit voluptatibus. Incidunt voluptatem sint doloribus deserunt dolor labore deserunt. Aut rerum sunt ex quia et et laborum. Ab accusamus magnam possimus quidem sed quas quibusdam quo.",
            "stock": 69,
            "sales": 21
        },
        {
            "id": 24,
            "category_id": 2,
            "reference": "Suit & Tie",
            "width": 37.85,
            "height": 36.98,
            "price": 73.08,
            "thumbnail": "https://marmelab.com/posters/business-5.jpeg",
            "image": "https://marmelab.com/posters/business-5.jpeg",
            "description": "Laboriosam esse ut corporis. Ullam sint est. Autem expedita quasi.",
            "stock": 0,
            "sales": 15
        },
        {
            "id": 25,
            "category_id": 2,
            "reference": "Shake Hands",
            "width": 10.07,
            "height": 21.43,
            "price": 11.02,
            "thumbnail": "https://marmelab.com/posters/business-6.jpeg",
            "image": "https://marmelab.com/posters/business-6.jpeg",
            "description": "Debitis sint ut sapiente. Molestiae repudiandae aut qui similique deleniti. Aut saepe ut ut ea dolore consequatur cumque culpa impedit. In quas sed illum dolorum qui ea atque.",
            "stock": 11,
            "sales": 18
        },
        {
            "id": 26,
            "category_id": 2,
            "reference": "Building Sky",
            "width": 19.33,
            "height": 16.98,
            "price": 17.31,
            "thumbnail": "https://marmelab.com/posters/business-7.jpeg",
            "image": "https://marmelab.com/posters/business-7.jpeg",
            "description": "Et et magni unde illum explicabo quae quo ad. Aperiam incidunt nihil tempore rerum corrupti saepe dolorem et eveniet. Sit est dolor corrupti totam voluptatum animi. Doloremque iste et sapiente ipsam sequi. Eaque est provident. Id reprehenderit vitae qui ipsum velit rerum soluta et consequuntur.",
            "stock": 64,
            "sales": 34
        },
        {
            "id": 27,
            "category_id": 2,
            "reference": "Yellow Pad",
            "width": 23.15,
            "height": 34.34,
            "price": 46.36,
            "thumbnail": "https://marmelab.com/posters/business-8.jpeg",
            "image": "https://marmelab.com/posters/business-8.jpeg",
            "description": "Maxime voluptate commodi ex dolorum ducimus molestias. Est porro fugit voluptatem delectus rem fugit. Numquam ea ab consequatur. Ducimus qui et cupiditate sunt. Placeat quisquam eos quam asperiores a quam deleniti delectus expedita. Quia necessitatibus exercitationem ea.",
            "stock": 78,
            "sales": 14
        },
        {
            "id": 28,
            "category_id": 2,
            "reference": "Work Devices",
            "width": 17.37,
            "height": 31.16,
            "price": 30.31,
            "thumbnail": "https://marmelab.com/posters/business-9.jpeg",
            "image": "https://marmelab.com/posters/business-9.jpeg",
            "description": "Minus minima et. Tempora perferendis voluptatibus eum nisi a id dolorem qui. Voluptatem ipsum fugit facilis. Harum ullam sint ab in sed explicabo repellat. Asperiores enim qui expedita dolores distinctio itaque aut quod.",
            "stock": 148,
            "sales": 19
        },
        {
            "id": 29,
            "category_id": 2,
            "reference": "Hands Clap",
            "width": 35.43,
            "height": 22.11,
            "price": 49.19,
            "thumbnail": "https://marmelab.com/posters/business-10.jpeg",
            "image": "https://marmelab.com/posters/business-10.jpeg",
            "description": "Provident aut aut quia itaque sit ab et quo aut. Fugit omnis saepe aspernatur enim adipisci voluptatem. Amet nobis explicabo et ex. Laudantium voluptas aliquid. Accusantium quos vel sint.",
            "stock": 0,
            "sales": 18
        },
        {
            "id": 30,
            "category_id": 3,
            "reference": "Old Combi",
            "width": 37.5,
            "height": 27.61,
            "price": 52.84,
            "thumbnail": "https://marmelab.com/posters/cars-1.jpeg",
            "image": "https://marmelab.com/posters/cars-1.jpeg",
            "description": "Exercitationem omnis et explicabo ad impedit vero sunt sint nesciunt. Minus possimus voluptatem magnam similique omnis nemo sapiente ipsa ut. Quia sit eligendi aut id dignissimos. Autem tempora quas et esse. Mollitia officiis est architecto nam molestiae suscipit dolor consequatur voluptatibus.",
            "stock": 5,
            "sales": 21
        },
        {
            "id": 31,
            "category_id": 3,
            "reference": "Asian Plates",
            "width": 32.62,
            "height": 13.3,
            "price": 28.02,
            "thumbnail": "https://marmelab.com/posters/cars-2.jpeg",
            "image": "https://marmelab.com/posters/cars-2.jpeg",
            "description": "Qui nihil quas. Quasi sed voluptas id et harum facere omnis. Neque consectetur quia ex.",
            "stock": 143,
            "sales": 20
        },
        {
            "id": 32,
            "category_id": 3,
            "reference": "Pedestrian Crossing",
            "width": 18.22,
            "height": 36.54,
            "price": 44.07,
            "thumbnail": "https://marmelab.com/posters/cars-3.jpeg",
            "image": "https://marmelab.com/posters/cars-3.jpeg",
            "description": "Sint sunt dignissimos sapiente consequatur similique vero. Incidunt numquam voluptatum officiis id iure nihil eum quos. Laboriosam minus excepturi et ratione quas non expedita dolor fugiat. Natus accusamus quia. Quia porro temporibus labore est amet et necessitatibus vel facere. Soluta harum ab repudiandae asperiores ratione suscipit quia.",
            "stock": 99,
            "sales": 14
        },
        {
            "id": 33,
            "category_id": 3,
            "reference": "Farmer Boy",
            "width": 39.46,
            "height": 21.39,
            "price": 42.39,
            "thumbnail": "https://marmelab.com/posters/cars-4.jpeg",
            "image": "https://marmelab.com/posters/cars-4.jpeg",
            "description": "Et et nihil non et sed veniam. Reiciendis minima ullam aut ut cumque ut magnam. Qui qui earum quae vel deleniti et tempora soluta. Ipsum aut voluptas vero eos ea cumque velit voluptatibus.",
            "stock": 34,
            "sales": 24
        },
        {
            "id": 34,
            "category_id": 3,
            "reference": "Make Over",
            "width": 34.53,
            "height": 37.81,
            "price": 72.17,
            "thumbnail": "https://marmelab.com/posters/cars-5.jpeg",
            "image": "https://marmelab.com/posters/cars-5.jpeg",
            "description": "Rerum culpa quia vel saepe aut quas dolores at. Totam odit ducimus iusto asperiores qui est delectus soluta. Maiores voluptatem qui minus. Ut iusto corporis et nisi adipisci alias aut nihil repellendus. Eius assumenda dolor voluptas tempora. Inventore voluptatem perferendis blanditiis amet quo.",
            "stock": 129,
            "sales": 17
        },
        {
            "id": 35,
            "category_id": 3,
            "reference": "Sports Sunset",
            "width": 10.92,
            "height": 14.89,
            "price": 8.79,
            "thumbnail": "https://marmelab.com/posters/cars-6.jpeg",
            "image": "https://marmelab.com/posters/cars-6.jpeg",
            "description": "Et facilis repudiandae provident rem sit. Sit mollitia dolore numquam voluptatibus aliquam rerum omnis incidunt. Dignissimos ducimus quis sunt quia labore omnis.",
            "stock": 37,
            "sales": 25
        },
        {
            "id": 36,
            "category_id": 3,
            "reference": "Desert Jeep",
            "width": 18.62,
            "height": 29.15,
            "price": 31.5,
            "thumbnail": "https://marmelab.com/posters/cars-7.jpeg",
            "image": "https://marmelab.com/posters/cars-7.jpeg",
            "description": "Voluptatem distinctio et provident deserunt. Exercitationem accusamus ducimus quae natus sint occaecati eos necessitatibus reiciendis. Voluptas voluptatem praesentium laudantium consequatur ut. Similique explicabo debitis provident sunt.",
            "stock": 11,
            "sales": 14
        },
        {
            "id": 37,
            "category_id": 3,
            "reference": "Highway Bridge",
            "width": 22.07,
            "height": 38.89,
            "price": 49.32,
            "thumbnail": "https://marmelab.com/posters/cars-8.jpeg",
            "image": "https://marmelab.com/posters/cars-8.jpeg",
            "description": "Quisquam inventore vel ipsam. Modi minus sunt enim et non nisi eos neque. Aut assumenda autem exercitationem repellendus sint.",
            "stock": 48,
            "sales": 30
        },
        {
            "id": 38,
            "category_id": 3,
            "reference": "Race Stickers",
            "width": 26.62,
            "height": 28.16,
            "price": 42.91,
            "thumbnail": "https://marmelab.com/posters/cars-9.jpeg",
            "image": "https://marmelab.com/posters/cars-9.jpeg",
            "description": "In debitis inventore. Fugiat ipsum et autem nihil eos expedita sed aut eveniet. Exercitationem est earum totam est. Qui nulla et quo nihil adipisci sed eum consequatur. Magni dolores explicabo consequatur non beatae.",
            "stock": 35,
            "sales": 25
        },
        {
            "id": 39,
            "category_id": 3,
            "reference": "White Deluxe",
            "width": 26.73,
            "height": 20.82,
            "price": 33.5,
            "thumbnail": "https://marmelab.com/posters/cars-10.jpeg",
            "image": "https://marmelab.com/posters/cars-10.jpeg",
            "description": "Mollitia laudantium dolor dignissimos atque. Est tempore earum est. Distinctio quisquam voluptatibus doloremque illo architecto.",
            "stock": 0,
            "sales": 19
        },
        {
            "id": 40,
            "category_id": 4,
            "reference": "Bridge Lights",
            "width": 18.99,
            "height": 13.68,
            "price": 14.3,
            "thumbnail": "https://marmelab.com/posters/city-1.jpeg",
            "image": "https://marmelab.com/posters/city-1.jpeg",
            "description": "Quo qui consequatur excepturi voluptate dolores doloribus non pariatur. Dolor enim cum eveniet molestiae. Non rerum quo minima mollitia sapiente vel distinctio. Occaecati est enim sit.",
            "stock": 89,
            "sales": 29
        },
        {
            "id": 41,
            "category_id": 4,
            "reference": "Color Dots",
            "width": 21.48,
            "height": 32.15,
            "price": 38.93,
            "thumbnail": "https://marmelab.com/posters/city-2.jpeg",
            "image": "https://marmelab.com/posters/city-2.jpeg",
            "description": "Quia deleniti officiis numquam neque recusandae nulla perferendis ea illum. Sit vitae sequi. Ducimus explicabo quae porro est tenetur.",
            "stock": 84,
            "sales": 10
        },
        {
            "id": 42,
            "category_id": 4,
            "reference": "Cloud Suspension",
            "width": 16.32,
            "height": 28.42,
            "price": 29.82,
            "thumbnail": "https://marmelab.com/posters/city-3.jpeg",
            "image": "https://marmelab.com/posters/city-3.jpeg",
            "description": "Voluptatum adipisci velit consequuntur quidem totam molestias. Quia maiores optio atque. Sed sunt accusamus voluptatibus voluptatem sed quia provident accusamus. Est illo voluptatem sapiente. Voluptatibus non ullam.",
            "stock": 85,
            "sales": 29
        },
        {
            "id": 43,
            "category_id": 4,
            "reference": "Paved Street",
            "width": 29.68,
            "height": 22.47,
            "price": 41.14,
            "thumbnail": "https://marmelab.com/posters/city-4.jpeg",
            "image": "https://marmelab.com/posters/city-4.jpeg",
            "description": "Odio laborum excepturi qui. Eum aut aut. Enim porro iste et qui et eaque molestias. Expedita sunt maxime sapiente iusto fugit tempore tenetur.",
            "stock": 38,
            "sales": 19
        },
        {
            "id": 44,
            "category_id": 4,
            "reference": "Blue Bay",
            "width": 22.75,
            "height": 19.09,
            "price": 26.43,
            "thumbnail": "https://marmelab.com/posters/city-5.jpeg",
            "image": "https://marmelab.com/posters/city-5.jpeg",
            "description": "Et nam temporibus pariatur fuga facilis nulla quo nihil. Ut quas odit labore sunt voluptate eos eos eum distinctio. Et explicabo quis qui autem dolorem hic. Quae aut doloremque odit voluptatum et nulla.",
            "stock": 135,
            "sales": 14
        },
        {
            "id": 45,
            "category_id": 4,
            "reference": "Wooden Door",
            "width": 32.99,
            "height": 10.85,
            "price": 19.09,
            "thumbnail": "https://marmelab.com/posters/city-6.jpeg",
            "image": "https://marmelab.com/posters/city-6.jpeg",
            "description": "Eligendi soluta nihil aspernatur voluptatibus corrupti perspiciatis qui voluptatibus cupiditate. Deleniti consequatur repudiandae. Modi dolores quis porro quod doloribus asperiores. Odio fugiat occaecati. Id inventore dignissimos incidunt ea.",
            "stock": 13,
            "sales": 28
        },
        {
            "id": 46,
            "category_id": 4,
            "reference": "Concrete Angles",
            "width": 11.97,
            "height": 26.55,
            "price": 18.82,
            "thumbnail": "https://marmelab.com/posters/city-7.jpeg",
            "image": "https://marmelab.com/posters/city-7.jpeg",
            "description": "Qui adipisci libero est aut. Aliquid minus corrupti nobis rerum numquam consectetur. Ipsa quam aliquam soluta accusantium officiis illum. Voluptatem sed est aut provident ut.",
            "stock": 65,
            "sales": 26
        },
        {
            "id": 47,
            "category_id": 4,
            "reference": "London Lights",
            "width": 20.84,
            "height": 29.34,
            "price": 39.8,
            "thumbnail": "https://marmelab.com/posters/city-8.jpeg",
            "image": "https://marmelab.com/posters/city-8.jpeg",
            "description": "Et voluptatem exercitationem cumque quidem hic. Sint ut similique. Aliquam necessitatibus ut accusamus quis et neque. Asperiores recusandae reprehenderit neque possimus nulla omnis dignissimos.",
            "stock": 87,
            "sales": 34
        },
        {
            "id": 48,
            "category_id": 4,
            "reference": "Fort Point",
            "width": 23.6,
            "height": 11.48,
            "price": 17.5,
            "thumbnail": "https://marmelab.com/posters/city-9.jpeg",
            "image": "https://marmelab.com/posters/city-9.jpeg",
            "description": "Qui ea eos provident. Quasi odit dolor. Quod ipsa quia iste voluptatem at minus esse.",
            "stock": 0,
            "sales": 9
        },
        {
            "id": 49,
            "category_id": 4,
            "reference": "Rainy Glass",
            "width": 19.59,
            "height": 31.85,
            "price": 41.13,
            "thumbnail": "https://marmelab.com/posters/city-10.jpeg",
            "image": "https://marmelab.com/posters/city-10.jpeg",
            "description": "Et recusandae autem reiciendis quas voluptates rerum. Reprehenderit optio sunt tempore voluptas suscipit sed ipsum est omnis. Itaque non ea in blanditiis modi consequatur. Minus aperiam temporibus doloribus fugit molestiae consequuntur veritatis est et. Amet sint aut dolores est nesciunt.",
            "stock": 136,
            "sales": 31
        },
        {
            "id": 50,
            "category_id": 5,
            "reference": "Apricot Tree",
            "width": 37.97,
            "height": 19.57,
            "price": 42.06,
            "thumbnail": "https://marmelab.com/posters/flowers-1.jpeg",
            "image": "https://marmelab.com/posters/flowers-1.jpeg",
            "description": "Et accusamus repellendus. Sed quasi neque. Ratione quis aut aliquam labore accusamus aut sunt voluptatem delectus. Deserunt doloribus eaque.",
            "stock": 106,
            "sales": 22
        },
        {
            "id": 51,
            "category_id": 5,
            "reference": "Orange Rose",
            "width": 37.44,
            "height": 17.4,
            "price": 38.75,
            "thumbnail": "https://marmelab.com/posters/flowers-2.jpeg",
            "image": "https://marmelab.com/posters/flowers-2.jpeg",
            "description": "Id quidem dolorem provident tempore molestiae at necessitatibus. Ut rerum facere. Esse perferendis ipsam et occaecati consequatur libero et. Incidunt et ullam qui. Qui possimus quas aut eligendi est voluptates. Molestias dolores consequatur sed.",
            "stock": 147,
            "sales": 25
        },
        {
            "id": 52,
            "category_id": 5,
            "reference": "Purple Petunia",
            "width": 33.07,
            "height": 35.71,
            "price": 77.64,
            "thumbnail": "https://marmelab.com/posters/flowers-3.jpeg",
            "image": "https://marmelab.com/posters/flowers-3.jpeg",
            "description": "Quaerat et ipsa dolorem iusto et assumenda quasi blanditiis. In rerum amet cupiditate. Maiores ipsam sit eos odit. Quis quam tenetur voluptatem aliquam earum. Neque aperiam qui nulla expedita aperiam delectus enim nesciunt.",
            "stock": 87,
            "sales": 13
        },
        {
            "id": 53,
            "category_id": 5,
            "reference": "Water Lily",
            "width": 28.36,
            "height": 21.5,
            "price": 38.51,
            "thumbnail": "https://marmelab.com/posters/flowers-4.jpeg",
            "image": "https://marmelab.com/posters/flowers-4.jpeg",
            "description": "Perferendis optio tempora. Numquam qui nemo aut earum. Ut qui sint ut modi explicabo in.",
            "stock": 109,
            "sales": 10
        },
        {
            "id": 54,
            "category_id": 5,
            "reference": "White Peony",
            "width": 28.05,
            "height": 14.18,
            "price": 21,
            "thumbnail": "https://marmelab.com/posters/flowers-5.jpeg",
            "image": "https://marmelab.com/posters/flowers-5.jpeg",
            "description": "Est veniam voluptatem explicabo exercitationem aut quas sunt quibusdam omnis. Atque et deserunt enim dolores nesciunt qui. Eos voluptates quod facere repellendus voluptas debitis quo praesentium. Vero et inventore nisi est est id. Eum error sunt adipisci dolor sed fugit quis odit hic.",
            "stock": 86,
            "sales": 21
        },
        {
            "id": 55,
            "category_id": 5,
            "reference": "Poppy Field",
            "width": 12.94,
            "height": 20.83,
            "price": 17.45,
            "thumbnail": "https://marmelab.com/posters/flowers-6.jpeg",
            "image": "https://marmelab.com/posters/flowers-6.jpeg",
            "description": "Natus laborum doloremque fuga. Assumenda et ipsam optio totam est et et vel fugit. Culpa delectus vitae qui voluptatem enim nostrum dolore. Ut voluptatem aut illo non libero laboriosam id et aut. Et ut exercitationem.",
            "stock": 53,
            "sales": 26
        },
        {
            "id": 56,
            "category_id": 5,
            "reference": "Blue Flax",
            "width": 39.51,
            "height": 10.79,
            "price": 28.37,
            "thumbnail": "https://marmelab.com/posters/flowers-7.jpeg",
            "image": "https://marmelab.com/posters/flowers-7.jpeg",
            "description": "Aspernatur vel porro consequatur placeat at ut. Quos ut sit numquam dolores. Qui vel quibusdam modi consequatur consequatur magnam. Velit sequi nulla fugit.",
            "stock": 0,
            "sales": 29
        },
        {
            "id": 57,
            "category_id": 5,
            "reference": "Love Roses",
            "width": 17.2,
            "height": 16.72,
            "price": 18.93,
            "thumbnail": "https://marmelab.com/posters/flowers-8.jpeg",
            "image": "https://marmelab.com/posters/flowers-8.jpeg",
            "description": "Aliquid est officia magni natus in quibusdam a maiores. Quia magnam beatae atque facilis quas impedit. Delectus consequatur nobis quia dolorem voluptatem at ea rerum doloremque.",
            "stock": 31,
            "sales": 31
        },
        {
            "id": 58,
            "category_id": 5,
            "reference": "California Poppy",
            "width": 19.37,
            "height": 13.95,
            "price": 17.42,
            "thumbnail": "https://marmelab.com/posters/flowers-9.jpeg",
            "image": "https://marmelab.com/posters/flowers-9.jpeg",
            "description": "Qui quos aliquam voluptatum. Voluptatem fugiat aperiam omnis et. Totam voluptas voluptas impedit provident voluptatem ut. Quam harum quia autem dolore quis nesciunt. Beatae esse quaerat.",
            "stock": 44,
            "sales": 22
        },
        {
            "id": 59,
            "category_id": 5,
            "reference": "Dalhia Colors",
            "width": 38.43,
            "height": 29.82,
            "price": 62.59,
            "thumbnail": "https://marmelab.com/posters/flowers-10.jpeg",
            "image": "https://marmelab.com/posters/flowers-10.jpeg",
            "description": "Qui dolorem omnis et. Molestiae a praesentium consequatur ullam expedita enim maiores distinctio. Sint est eaque et voluptatem optio reiciendis.",
            "stock": 67,
            "sales": 9
        },
        {
            "id": 60,
            "category_id": 6,
            "reference": "Fuzzy Forks",
            "width": 36.49,
            "height": 17.59,
            "price": 36.31,
            "thumbnail": "https://marmelab.com/posters/food-1.jpeg",
            "image": "https://marmelab.com/posters/food-1.jpeg",
            "description": "Sint pariatur et veniam error odit. Architecto deserunt rem. Mollitia occaecati quia.",
            "stock": 140,
            "sales": 16
        },
        {
            "id": 61,
            "category_id": 6,
            "reference": "Stamp Mug",
            "width": 29.76,
            "height": 19.09,
            "price": 35.46,
            "thumbnail": "https://marmelab.com/posters/food-2.jpeg",
            "image": "https://marmelab.com/posters/food-2.jpeg",
            "description": "Enim et eos quis nemo repudiandae eaque quidem molestiae. Sit corrupti autem ut temporibus ratione esse temporibus ex nisi. Suscipit eos voluptate sint voluptas.",
            "stock": 88,
            "sales": 23
        },
        {
            "id": 62,
            "category_id": 6,
            "reference": "Two Expressos",
            "width": 26.88,
            "height": 28.08,
            "price": 48.01,
            "thumbnail": "https://marmelab.com/posters/food-3.jpeg",
            "image": "https://marmelab.com/posters/food-3.jpeg",
            "description": "Dolore aut inventore et harum expedita in voluptatem aut. Quo recusandae autem. Pariatur sit ex eos blanditiis qui. Est et qui qui voluptas voluptates consequatur et quis dolorem. Molestias consequatur amet est cupiditate vitae et.",
            "stock": 65,
            "sales": 14
        },
        {
            "id": 63,
            "category_id": 6,
            "reference": "Red Latte",
            "width": 33.91,
            "height": 36.12,
            "price": 72.7,
            "thumbnail": "https://marmelab.com/posters/food-4.jpeg",
            "image": "https://marmelab.com/posters/food-4.jpeg",
            "description": "Cupiditate nemo deserunt natus eos ullam ea nisi. Est aliquid et quia quia excepturi accusantium. Nobis quam cumque id est impedit sit.",
            "stock": 2,
            "sales": 19
        },
        {
            "id": 64,
            "category_id": 6,
            "reference": "Black Grapes",
            "width": 23.44,
            "height": 36.66,
            "price": 53.93,
            "thumbnail": "https://marmelab.com/posters/food-5.jpeg",
            "image": "https://marmelab.com/posters/food-5.jpeg",
            "description": "Incidunt consequatur non quas molestiae excepturi eos natus dolores. Et qui velit et sed quis omnis eveniet. Aut sit quis est dolorem et autem consectetur. Ex incidunt nisi sapiente rerum dolores numquam doloremque ut consequatur. Rerum consequatur aut at fugit sunt ea dolorem.",
            "stock": 0,
            "sales": 22
        },
        {
            "id": 65,
            "category_id": 6,
            "reference": "Forgotten Strawberries",
            "width": 26.05,
            "height": 29.6,
            "price": 44.28,
            "thumbnail": "https://marmelab.com/posters/food-6.jpeg",
            "image": "https://marmelab.com/posters/food-6.jpeg",
            "description": "Numquam cupiditate possimus voluptatem est velit sit quaerat hic optio. Est praesentium rem tempore perspiciatis aut voluptatibus blanditiis id. Assumenda sequi molestiae unde eum repudiandae. Qui aut ullam laboriosam. Ducimus nostrum ut adipisci.",
            "stock": 10,
            "sales": 18
        },
        {
            "id": 66,
            "category_id": 6,
            "reference": "Close Steam",
            "width": 35.46,
            "height": 14.75,
            "price": 28.39,
            "thumbnail": "https://marmelab.com/posters/food-7.jpeg",
            "image": "https://marmelab.com/posters/food-7.jpeg",
            "description": "Dolorem qui doloribus porro impedit necessitatibus. Possimus consequatur eum ab. Quo accusantium recusandae animi est. Aut sint ut consequatur aut. Minima sed ut.",
            "stock": 0,
            "sales": 27
        },
        {
            "id": 67,
            "category_id": 6,
            "reference": "Brewing Tea",
            "width": 28.39,
            "height": 11.68,
            "price": 21.05,
            "thumbnail": "https://marmelab.com/posters/food-8.jpeg",
            "image": "https://marmelab.com/posters/food-8.jpeg",
            "description": "Et eos laborum ullam cupiditate quae earum natus qui sequi. Recusandae quos delectus adipisci quis quis quae quidem ipsam. Accusantium tempore voluptas facere qui ullam aut. Repellendus consequuntur deserunt accusamus repudiandae officiis ut. At ipsam accusamus voluptas unde possimus quae nulla aut labore. Voluptatem soluta aut nobis.",
            "stock": 25,
            "sales": 10
        },
        {
            "id": 68,
            "category_id": 6,
            "reference": "Red Onions",
            "width": 18.77,
            "height": 25.08,
            "price": 25.22,
            "thumbnail": "https://marmelab.com/posters/food-9.jpeg",
            "image": "https://marmelab.com/posters/food-9.jpeg",
            "description": "Harum modi omnis deserunt est nobis eius accusamus voluptatem sed. Sunt animi pariatur sit temporibus. Odit sapiente ea et tenetur quia ea aut. Reiciendis illum iure est cumque culpa illum soluta fugit. Et aut voluptates. Et molestiae et commodi pariatur totam.",
            "stock": 96,
            "sales": 31
        },
        {
            "id": 69,
            "category_id": 6,
            "reference": "Dark Honey",
            "width": 37,
            "height": 32.66,
            "price": 77.07,
            "thumbnail": "https://marmelab.com/posters/food-10.jpeg",
            "image": "https://marmelab.com/posters/food-10.jpeg",
            "description": "At ipsum dolorum hic necessitatibus nam ipsa. Autem dolor quia aut sed eligendi vero esse eos voluptas. At qui aut consectetur eum itaque ratione voluptatem. Et porro fugit cumque magnam debitis.",
            "stock": 109,
            "sales": 12
        },
        {
            "id": 70,
            "category_id": 7,
            "reference": "Distant Mountains",
            "width": 28.45,
            "height": 30.74,
            "price": 57.97,
            "thumbnail": "https://marmelab.com/posters/nature-1.jpeg",
            "image": "https://marmelab.com/posters/nature-1.jpeg",
            "description": "Maxime omnis voluptas quia nihil facilis eum. Rerum recusandae aperiam expedita laboriosam sit consectetur qui facilis eveniet. Nam enim atque perferendis corrupti.",
            "stock": 17,
            "sales": 29
        },
        {
            "id": 71,
            "category_id": 7,
            "reference": "Fog Pond",
            "width": 10.39,
            "height": 22.29,
            "price": 15.08,
            "thumbnail": "https://marmelab.com/posters/nature-2.jpeg",
            "image": "https://marmelab.com/posters/nature-2.jpeg",
            "description": "Soluta praesentium iusto qui et omnis voluptatem et. Esse aliquid illum. Consequuntur neque enim corrupti minus omnis magni rem tempore sed. Enim corporis aperiam autem perferendis ratione dolor.",
            "stock": 76,
            "sales": 18
        },
        {
            "id": 72,
            "category_id": 7,
            "reference": "Sand Rocks",
            "width": 17.04,
            "height": 37.26,
            "price": 32.48,
            "thumbnail": "https://marmelab.com/posters/nature-3.jpeg",
            "image": "https://marmelab.com/posters/nature-3.jpeg",
            "description": "Quaerat delectus qui dolorum aut inventore sint magni praesentium. Enim ea quos hic veniam sed. Et et ut a sit et. Repellat eum qui doloribus officiis eveniet provident dolor veniam architecto.",
            "stock": 148,
            "sales": 36
        },
        {
            "id": 73,
            "category_id": 7,
            "reference": "Pebble Shore",
            "width": 29.62,
            "height": 14.43,
            "price": 21.7,
            "thumbnail": "https://marmelab.com/posters/nature-4.jpeg",
            "image": "https://marmelab.com/posters/nature-4.jpeg",
            "description": "Maiores quibusdam vel harum. Sunt eum sed. Molestias adipisci ducimus debitis et sunt.",
            "stock": 121,
            "sales": 13
        },
        {
            "id": 74,
            "category_id": 7,
            "reference": "Eroded Fractals",
            "width": 15.3,
            "height": 27.26,
            "price": 22.01,
            "thumbnail": "https://marmelab.com/posters/nature-5.jpeg",
            "image": "https://marmelab.com/posters/nature-5.jpeg",
            "description": "Et provident a ipsum. In autem nostrum dicta voluptatibus dicta dolor sint. Aliquid facilis et rem et quos.",
            "stock": 53,
            "sales": 31
        },
        {
            "id": 75,
            "category_id": 7,
            "reference": "Water Fall",
            "width": 25.38,
            "height": 26.45,
            "price": 34.29,
            "thumbnail": "https://marmelab.com/posters/nature-6.jpeg",
            "image": "https://marmelab.com/posters/nature-6.jpeg",
            "description": "Modi est repudiandae facilis autem eum. Voluptas nostrum totam quae nam doloremque. Placeat voluptatibus ab velit. Est facere delectus. Aliquam voluptate ea alias accusantium.",
            "stock": 29,
            "sales": 35
        },
        {
            "id": 76,
            "category_id": 7,
            "reference": "Drif Wood",
            "width": 39.48,
            "height": 37.77,
            "price": 86.69,
            "thumbnail": "https://marmelab.com/posters/nature-7.jpeg",
            "image": "https://marmelab.com/posters/nature-7.jpeg",
            "description": "Quis dolorem nihil consequatur dignissimos alias temporibus nostrum illo ut. Recusandae officiis molestiae ea suscipit possimus sint est rerum. Enim eaque autem quia occaecati et delectus velit aut. Quis cum aut pariatur quis qui iste.",
            "stock": 100,
            "sales": 25
        },
        {
            "id": 77,
            "category_id": 7,
            "reference": "Dirt Track",
            "width": 11.06,
            "height": 32.85,
            "price": 20.57,
            "thumbnail": "https://marmelab.com/posters/nature-8.jpeg",
            "image": "https://marmelab.com/posters/nature-8.jpeg",
            "description": "Quam voluptatum dolores error. Quasi aliquid exercitationem sed natus aut rerum labore ut. At veritatis non voluptate voluptatum dolor eius et.",
            "stock": 122,
            "sales": 20
        },
        {
            "id": 78,
            "category_id": 7,
            "reference": "Green Grass",
            "width": 14.02,
            "height": 36.58,
            "price": 29.82,
            "thumbnail": "https://marmelab.com/posters/nature-9.jpeg",
            "image": "https://marmelab.com/posters/nature-9.jpeg",
            "description": "Voluptate rerum cumque quaerat ut et aut natus et aut. Facilis vel et ut tempore provident aliquam aut quidem. Soluta eligendi cumque rerum maxime delectus. Fuga vero corporis dolor et aperiam quia fugiat perferendis. Vitae modi aperiam laboriosam quod aut.",
            "stock": 0,
            "sales": 19
        },
        {
            "id": 79,
            "category_id": 7,
            "reference": "Yellow Lichen",
            "width": 11.22,
            "height": 24.06,
            "price": 13.78,
            "thumbnail": "https://marmelab.com/posters/nature-10.jpeg",
            "image": "https://marmelab.com/posters/nature-10.jpeg",
            "description": "Qui beatae dolores ad cupiditate praesentium. Et aliquam voluptatem sapiente nam est qui sed est. Qui quibusdam est ipsum ut est consequatur officiis. Enim unde consequatur nostrum dolor hic impedit. Suscipit ut minima consequatur voluptatem sit facilis et quo porro. Sed commodi odio harum aperiam rerum quisquam iusto iure sint.",
            "stock": 92,
            "sales": 26
        },
        {
            "id": 80,
            "category_id": 8,
            "reference": "Crossing Alone",
            "width": 11.72,
            "height": 19.2,
            "price": 12.1,
            "thumbnail": "https://marmelab.com/posters/people-1.jpeg",
            "image": "https://marmelab.com/posters/people-1.jpeg",
            "description": "Fugit ex dolorem et earum enim. Quidem sunt et quaerat iste autem est et voluptatum. Porro laborum voluptates temporibus tenetur libero et placeat unde rem. Dicta sapiente voluptatum. Facere neque praesentium.",
            "stock": 71,
            "sales": 26
        },
        {
            "id": 81,
            "category_id": 8,
            "reference": "Budding Grove",
            "width": 26.48,
            "height": 35.8,
            "price": 48.66,
            "thumbnail": "https://marmelab.com/posters/people-2.jpeg",
            "image": "https://marmelab.com/posters/people-2.jpeg",
            "description": "Fugiat sint et. Expedita aut rerum sit aspernatur maxime. Non harum blanditiis totam distinctio et quis quis odio ut.",
            "stock": 51,
            "sales": 17
        },
        {
            "id": 82,
            "category_id": 8,
            "reference": "Light Hair",
            "width": 16.01,
            "height": 20.78,
            "price": 16.93,
            "thumbnail": "https://marmelab.com/posters/people-3.jpeg",
            "image": "https://marmelab.com/posters/people-3.jpeg",
            "description": "Dicta placeat quam ut et iure tempora voluptatem recusandae eveniet. Sequi aut voluptas sint ut. Voluptatum iure totam provident facilis. Voluptatem in reprehenderit aspernatur. Natus aliquam rerum aliquam voluptate rem non.",
            "stock": 120,
            "sales": 17
        },
        {
            "id": 83,
            "category_id": 8,
            "reference": "Black & White",
            "width": 39.56,
            "height": 27.85,
            "price": 73,
            "thumbnail": "https://marmelab.com/posters/people-4.jpeg",
            "image": "https://marmelab.com/posters/people-4.jpeg",
            "description": "Eum ex repellat ipsum dolor natus illo quis ut. Ea nostrum est qui consequatur officia excepturi vitae recusandae. Rerum hic et.",
            "stock": 76,
            "sales": 20
        },
        {
            "id": 84,
            "category_id": 8,
            "reference": "Rock Concert",
            "width": 37.64,
            "height": 20.82,
            "price": 52.09,
            "thumbnail": "https://marmelab.com/posters/people-5.jpeg",
            "image": "https://marmelab.com/posters/people-5.jpeg",
            "description": "Quisquam quis sed beatae. Qui amet soluta asperiores. Mollitia quas alias modi accusamus.",
            "stock": 88,
            "sales": 21
        },
        {
            "id": 85,
            "category_id": 8,
            "reference": "Meeting Bench",
            "width": 23.69,
            "height": 23.92,
            "price": 34.88,
            "thumbnail": "https://marmelab.com/posters/people-6.jpeg",
            "image": "https://marmelab.com/posters/people-6.jpeg",
            "description": "Aut dolores ipsum non quos quis aut rerum. Libero eligendi magnam dolor odit ratione et. Nulla optio eveniet error cupiditate fugit dicta. Est occaecati sed quas. Sequi temporibus et quia debitis cumque quia. Omnis rem saepe accusantium molestias sunt dicta rem hic et.",
            "stock": 66,
            "sales": 22
        },
        {
            "id": 86,
            "category_id": 8,
            "reference": "Son & Lumière",
            "width": 32.96,
            "height": 30.94,
            "price": 53.08,
            "thumbnail": "https://marmelab.com/posters/people-7.jpeg",
            "image": "https://marmelab.com/posters/people-7.jpeg",
            "description": "Ad repudiandae sed dolores voluptatem culpa ut sed. Qui quaerat aspernatur occaecati occaecati quam. Ut quia cumque. Et nihil eos magni rerum modi sequi blanditiis. Sint dolor sit vel fuga quis id similique minima. Ipsa ut corporis et eum numquam maxime molestiae omnis in.",
            "stock": 0,
            "sales": 15
        },
        {
            "id": 87,
            "category_id": 8,
            "reference": "Running Boy",
            "width": 20.11,
            "height": 18.75,
            "price": 20.43,
            "thumbnail": "https://marmelab.com/posters/people-8.jpeg",
            "image": "https://marmelab.com/posters/people-8.jpeg",
            "description": "Reprehenderit temporibus est architecto alias corrupti. Temporibus et incidunt fugiat atque libero rerum. Dolores consequatur nostrum qui blanditiis ut modi blanditiis qui sint. Impedit corporis repudiandae nesciunt temporibus eveniet. Eveniet iusto atque.",
            "stock": 100,
            "sales": 21
        },
        {
            "id": 88,
            "category_id": 8,
            "reference": "Dining Hall",
            "width": 25.18,
            "height": 37.38,
            "price": 60.46,
            "thumbnail": "https://marmelab.com/posters/people-9.jpeg",
            "image": "https://marmelab.com/posters/people-9.jpeg",
            "description": "Minima non earum nostrum reprehenderit dignissimos. Ut ad distinctio non fugiat ut. Iste architecto maxime. Officia qui voluptatem eum non.",
            "stock": 16,
            "sales": 28
        },
        {
            "id": 89,
            "category_id": 8,
            "reference": "Tunnel People",
            "width": 30.05,
            "height": 33.08,
            "price": 54.02,
            "thumbnail": "https://marmelab.com/posters/people-10.jpeg",
            "image": "https://marmelab.com/posters/people-10.jpeg",
            "description": "Voluptate repellat cum velit ullam ut ea voluptatum accusamus nesciunt. Soluta pariatur in et. Asperiores cumque dignissimos et voluptatem temporibus aut delectus nihil architecto. Debitis velit ipsum dolores. Amet labore quisquam minus. Asperiores harum omnis alias iure molestiae cumque dolor vel.",
            "stock": 100,
            "sales": 40
        },
        {
            "id": 90,
            "category_id": 9,
            "reference": "Feather Ball",
            "width": 26.28,
            "height": 22.08,
            "price": 35.97,
            "thumbnail": "https://marmelab.com/posters/sports-1.jpeg",
            "image": "https://marmelab.com/posters/sports-1.jpeg",
            "description": "Voluptatem provident aliquam minus. Necessitatibus quo minima doloribus eius reiciendis accusamus laboriosam esse. Accusamus hic est ut hic. Tenetur doloremque dolores similique facere dolores repudiandae.",
            "stock": 46,
            "sales": 32
        },
        {
            "id": 91,
            "category_id": 9,
            "reference": "Wall Skate",
            "width": 16.04,
            "height": 21.17,
            "price": 21.98,
            "thumbnail": "https://marmelab.com/posters/sports-2.jpeg",
            "image": "https://marmelab.com/posters/sports-2.jpeg",
            "description": "Veniam unde reiciendis exercitationem deserunt ea asperiores optio facere atque. Doloribus commodi error atque. Reiciendis ducimus blanditiis veniam neque quam alias placeat. Quas aspernatur enim consequatur quis. Repellendus tempore voluptatem ex quas sint doloremque reiciendis alias.",
            "stock": 49,
            "sales": 30
        },
        {
            "id": 92,
            "category_id": 9,
            "reference": "Kick Flip",
            "width": 23.84,
            "height": 14.61,
            "price": 18.74,
            "thumbnail": "https://marmelab.com/posters/sports-3.jpeg",
            "image": "https://marmelab.com/posters/sports-3.jpeg",
            "description": "Minus illum sunt quisquam commodi. Voluptas voluptatem voluptates sed nulla quidem sapiente quis laboriosam. Velit sapiente facere velit cumque aut dolores nisi ut est. Harum velit occaecati aut iusto libero harum facilis amet recusandae. Natus in consequatur est nulla explicabo et laudantium est et. Rerum animi quia quia ut sint quod non asperiores quia.",
            "stock": 91,
            "sales": 16
        },
        {
            "id": 93,
            "category_id": 9,
            "reference": "Down Hill",
            "width": 16.53,
            "height": 17.75,
            "price": 17.03,
            "thumbnail": "https://marmelab.com/posters/sports-4.jpeg",
            "image": "https://marmelab.com/posters/sports-4.jpeg",
            "description": "Provident a dolor in autem. Eos asperiores laborum et omnis dolorem reiciendis dicta at. Dolores cum est aut dolores provident distinctio eaque. Assumenda dolor possimus quos ipsam repellat dolor molestiae. Optio adipisci ipsam est qui qui eum ut. Velit quo ad maxime dolorem voluptas.",
            "stock": 57,
            "sales": 28
        },
        {
            "id": 94,
            "category_id": 9,
            "reference": "Baseball Night",
            "width": 13.57,
            "height": 13.83,
            "price": 11.86,
            "thumbnail": "https://marmelab.com/posters/sports-5.jpeg",
            "image": "https://marmelab.com/posters/sports-5.jpeg",
            "description": "Dolor autem similique. Ducimus ex quae delectus veniam. Ipsam qui et ex aut omnis optio et debitis. Natus consequatur dolorem recusandae nostrum deleniti esse consequatur iure. Laboriosam velit architecto aut similique impedit laborum a nihil.",
            "stock": 20,
            "sales": 20
        },
        {
            "id": 95,
            "category_id": 9,
            "reference": "Touch Line",
            "width": 31.61,
            "height": 18,
            "price": 29.18,
            "thumbnail": "https://marmelab.com/posters/sports-6.jpeg",
            "image": "https://marmelab.com/posters/sports-6.jpeg",
            "description": "Asperiores voluptas nobis magni dolorum dignissimos fugit et. Pariatur earum fugit assumenda quidem eum voluptate libero consequatur animi. Ab soluta reiciendis.",
            "stock": 116,
            "sales": 13
        },
        {
            "id": 96,
            "category_id": 9,
            "reference": "Alone Jogger",
            "width": 25.61,
            "height": 29.85,
            "price": 48.69,
            "thumbnail": "https://marmelab.com/posters/sports-7.jpeg",
            "image": "https://marmelab.com/posters/sports-7.jpeg",
            "description": "Aspernatur odit nihil quae rerum delectus architecto nihil rerum. Quia facere harum rem excepturi vitae ratione et animi. Dolorem quo hic veritatis neque eaque voluptate vero et. Temporibus id optio.",
            "stock": 30,
            "sales": 28
        },
        {
            "id": 97,
            "category_id": 9,
            "reference": "Green Basket",
            "width": 12.12,
            "height": 32.74,
            "price": 22.62,
            "thumbnail": "https://marmelab.com/posters/sports-8.jpeg",
            "image": "https://marmelab.com/posters/sports-8.jpeg",
            "description": "Non necessitatibus quis maxime qui. Tenetur nam ratione tempore ut dolore. Similique molestiae earum et magnam. Qui non qui. Cupiditate consequatur non nobis eius consequatur reprehenderit ullam et.",
            "stock": 117,
            "sales": 29
        },
        {
            "id": 98,
            "category_id": 9,
            "reference": "Mud Hug",
            "width": 12.45,
            "height": 35.56,
            "price": 29.34,
            "thumbnail": "https://marmelab.com/posters/sports-9.jpeg",
            "image": "https://marmelab.com/posters/sports-9.jpeg",
            "description": "Repudiandae omnis esse illo. Cum sequi consequatur cum nam alias delectus. Debitis non iusto voluptas iste quia blanditiis qui.",
            "stock": 100,
            "sales": 15
        },
        {
            "id": 99,
            "category_id": 9,
            "reference": "Metal Cycle",
            "width": 14.34,
            "height": 22.12,
            "price": 18.24,
            "thumbnail": "https://marmelab.com/posters/sports-10.jpeg",
            "image": "https://marmelab.com/posters/sports-10.jpeg",
            "description": "At delectus aut occaecati excepturi id quod. Dolores sit veniam harum. Dolores necessitatibus odio officia ad.",
            "stock": 43,
            "sales": 15
        },
        {
            "id": 100,
            "category_id": 10,
            "reference": "Black Screen",
            "width": 28.63,
            "height": 13.31,
            "price": 19.8,
            "thumbnail": "https://marmelab.com/posters/tech-1.jpeg",
            "image": "https://marmelab.com/posters/tech-1.jpeg",
            "description": "Ullam impedit maiores. Quisquam libero assumenda et officiis suscipit laboriosam quo quas. Unde ipsum officiis voluptas ut ipsa. Ut aspernatur et expedita sed ea et eligendi.",
            "stock": 34,
            "sales": 24
        },
        {
            "id": 101,
            "category_id": 10,
            "reference": "Phone Call",
            "width": 38.14,
            "height": 21.3,
            "price": 52.74,
            "thumbnail": "https://marmelab.com/posters/tech-2.jpeg",
            "image": "https://marmelab.com/posters/tech-2.jpeg",
            "description": "Ducimus et qui aperiam voluptatem. Repellat pariatur sed. Et omnis ipsam repellendus illo ea non cupiditate et rerum. Quia dolorem quos quia doloremque et omnis et sunt quidem.",
            "stock": 1,
            "sales": 28
        },
        {
            "id": 102,
            "category_id": 10,
            "reference": "Tablet & Phone",
            "width": 30.95,
            "height": 24.06,
            "price": 38.83,
            "thumbnail": "https://marmelab.com/posters/tech-3.jpeg",
            "image": "https://marmelab.com/posters/tech-3.jpeg",
            "description": "Similique et delectus aliquam quo voluptatem voluptas ducimus. Doloremque beatae doloribus et. Corporis veritatis autem. Et dignissimos laudantium iste ad magnam eos.",
            "stock": 75,
            "sales": 15
        },
        {
            "id": 103,
            "category_id": 10,
            "reference": "No Battery",
            "width": 39.28,
            "height": 21.75,
            "price": 52.78,
            "thumbnail": "https://marmelab.com/posters/tech-4.jpeg",
            "image": "https://marmelab.com/posters/tech-4.jpeg",
            "description": "Ullam pariatur impedit aliquam eveniet non aperiam. Et amet quaerat quia unde. Porro cupiditate quia porro sit. Autem nesciunt quas et. Qui qui rerum repudiandae assumenda blanditiis.",
            "stock": 0,
            "sales": 18
        },
        {
            "id": 104,
            "category_id": 10,
            "reference": "Phone Book",
            "width": 38.48,
            "height": 23.21,
            "price": 57.01,
            "thumbnail": "https://marmelab.com/posters/tech-5.jpeg",
            "image": "https://marmelab.com/posters/tech-5.jpeg",
            "description": "Velit cum excepturi sunt unde ut magni quia quae. Modi ut vel. Consequatur vel qui unde sit.",
            "stock": 27,
            "sales": 31
        },
        {
            "id": 105,
            "category_id": 10,
            "reference": "Camera Parts",
            "width": 28.05,
            "height": 34.87,
            "price": 58.69,
            "thumbnail": "https://marmelab.com/posters/tech-6.jpeg",
            "image": "https://marmelab.com/posters/tech-6.jpeg",
            "description": "Numquam quis esse reiciendis occaecati ad ut veniam. Praesentium voluptates aut maiores. Culpa eum quisquam omnis fuga rerum accusamus. Iusto odit inventore. Eveniet ex hic vel pariatur. Eligendi dolorem omnis eum.",
            "stock": 95,
            "sales": 14
        },
        {
            "id": 106,
            "category_id": 10,
            "reference": "Fuzzy Phone",
            "width": 26.3,
            "height": 13.99,
            "price": 24.4,
            "thumbnail": "https://marmelab.com/posters/tech-7.jpeg",
            "image": "https://marmelab.com/posters/tech-7.jpeg",
            "description": "Temporibus enim dolor tempora quae sit excepturi. Ut fugiat ipsum asperiores et illo maiores. Consequatur sit rem. Odit eius vero illum inventore aliquid eveniet soluta maiores. Quia esse id modi ratione et iusto excepturi.",
            "stock": 112,
            "sales": 23
        },
        {
            "id": 107,
            "category_id": 10,
            "reference": "Music & Light",
            "width": 35.94,
            "height": 17.38,
            "price": 41.26,
            "thumbnail": "https://marmelab.com/posters/tech-8.jpeg",
            "image": "https://marmelab.com/posters/tech-8.jpeg",
            "description": "Mollitia dolores natus. Quo commodi quisquam qui blanditiis nesciunt voluptas aliquam. Ut libero est est. Eos corporis velit aperiam voluptates a ut placeat. Adipisci ea officiis corporis suscipit nihil eveniet hic ut. Odio nihil porro rerum porro quia.",
            "stock": 9,
            "sales": 23
        },
        {
            "id": 108,
            "category_id": 10,
            "reference": "Eye Rest",
            "width": 31.86,
            "height": 20.33,
            "price": 37.4,
            "thumbnail": "https://marmelab.com/posters/tech-9.jpeg",
            "image": "https://marmelab.com/posters/tech-9.jpeg",
            "description": "Ut magni recusandae quibusdam aut ea vel. Dolor laudantium dolorum dolores voluptatum quas quaerat officiis. Eius laboriosam et quisquam hic a ea. Quaerat maiores saepe dolor reprehenderit aut id consequatur vel voluptatem. Aut eos quia et vel. Fugit inventore nisi ducimus molestias fuga.",
            "stock": 131,
            "sales": 35
        },
        {
            "id": 109,
            "category_id": 10,
            "reference": "Aligned Parts",
            "width": 18.01,
            "height": 31.5,
            "price": 34.19,
            "thumbnail": "https://marmelab.com/posters/tech-10.jpeg",
            "image": "https://marmelab.com/posters/tech-10.jpeg",
            "description": "Odio commodi ullam et. Quibusdam atque totam similique facere ipsum voluptates. Voluptas aut vitae excepturi doloremque.",
            "stock": 47,
            "sales": 15
        },
        {
            "id": 110,
            "category_id": 11,
            "reference": "Distant Jet",
            "width": 30.21,
            "height": 36.27,
            "price": 71.57,
            "thumbnail": "https://marmelab.com/posters/travel-1.jpeg",
            "image": "https://marmelab.com/posters/travel-1.jpeg",
            "description": "Sint ut et nam consequatur temporibus incidunt eum enim optio. Quia temporibus rerum deleniti in rerum similique. Architecto corporis dolorem adipisci aliquam id beatae eos perferendis molestiae. Fugiat est sequi ut pariatur iste. Omnis sed ut omnis qui. Harum veniam inventore mollitia accusamus.",
            "stock": 20,
            "sales": 28
        },
        {
            "id": 111,
            "category_id": 11,
            "reference": "Foggy Beach",
            "width": 22.03,
            "height": 33.32,
            "price": 42.52,
            "thumbnail": "https://marmelab.com/posters/travel-2.jpeg",
            "image": "https://marmelab.com/posters/travel-2.jpeg",
            "description": "Rerum omnis nisi ab in modi ut nisi aliquid. Exercitationem consequatur et nisi mollitia repudiandae. Facilis qui et dolore. Officia quis laboriosam et sint quam nam rerum consequatur. Accusantium sunt est id aliquam ipsa. Nesciunt similique facilis minus voluptatem in voluptatem maxime ullam.",
            "stock": 119,
            "sales": 19
        },
        {
            "id": 112,
            "category_id": 11,
            "reference": "White Lime",
            "width": 10.68,
            "height": 20.49,
            "price": 13.3,
            "thumbnail": "https://marmelab.com/posters/travel-3.jpeg",
            "image": "https://marmelab.com/posters/travel-3.jpeg",
            "description": "Provident perferendis reprehenderit esse ad qui nulla. Fugit sint esse culpa minus et non ducimus commodi. Error dolorem magni est.",
            "stock": 94,
            "sales": 15
        },
        {
            "id": 113,
            "category_id": 11,
            "reference": "Mysterious Cloud",
            "width": 17.8,
            "height": 30.28,
            "price": 28.42,
            "thumbnail": "https://marmelab.com/posters/travel-4.jpeg",
            "image": "https://marmelab.com/posters/travel-4.jpeg",
            "description": "Deserunt porro laborum dolores rerum incidunt aliquid nam. Ea sit doloribus soluta sapiente qui. Voluptatem at voluptas assumenda. Molestiae labore commodi similique. Laboriosam corporis omnis est est reprehenderit corrupti neque sed. Sit quam molestiae placeat esse aut alias qui.",
            "stock": 55,
            "sales": 34
        },
        {
            "id": 114,
            "category_id": 11,
            "reference": "Mountain Top",
            "width": 10.3,
            "height": 11.93,
            "price": 6.34,
            "thumbnail": "https://marmelab.com/posters/travel-5.jpeg",
            "image": "https://marmelab.com/posters/travel-5.jpeg",
            "description": "Blanditiis debitis atque ut aliquam quis iure. Consequatur et maxime perspiciatis. Perspiciatis adipisci quo nemo hic alias fugit. Est impedit excepturi laboriosam aut delectus qui consequatur aliquam. Necessitatibus molestiae voluptas in quasi sapiente facilis libero laboriosam et. Ducimus ut accusantium numquam ratione.",
            "stock": 0,
            "sales": 23
        },
        {
            "id": 115,
            "category_id": 11,
            "reference": "Light House",
            "width": 18.9,
            "height": 32,
            "price": 31.55,
            "thumbnail": "https://marmelab.com/posters/travel-6.jpeg",
            "image": "https://marmelab.com/posters/travel-6.jpeg",
            "description": "Ipsa numquam eaque voluptatem esse. Necessitatibus accusantium tenetur. Praesentium delectus vel corporis maxime. Dolorem quis quia.",
            "stock": 146,
            "sales": 16
        },
        {
            "id": 116,
            "category_id": 11,
            "reference": "Gray Day",
            "width": 16.57,
            "height": 34.71,
            "price": 31.53,
            "thumbnail": "https://marmelab.com/posters/travel-7.jpeg",
            "image": "https://marmelab.com/posters/travel-7.jpeg",
            "description": "Aut ipsam aut voluptatum ut qui dolorem fugit doloremque et. Fugiat et vero vitae quo. Sit velit fugiat ut nulla voluptas aperiam magnam ipsam. In voluptatibus incidunt et. Fuga cupiditate sequi pariatur sit cupiditate et. Possimus voluptas nisi aliquid laudantium quam voluptatum modi totam aperiam.",
            "stock": 73,
            "sales": 16
        },
        {
            "id": 117,
            "category_id": 11,
            "reference": "Desert Walkway",
            "width": 35.37,
            "height": 29.44,
            "price": 68.09,
            "thumbnail": "https://marmelab.com/posters/travel-8.jpeg",
            "image": "https://marmelab.com/posters/travel-8.jpeg",
            "description": "Vel iure consequatur est eos in sequi et asperiores. Dolorem ea dolorem impedit minus voluptatem voluptas dolorum atque vero. Tempora esse dolor repellat qui rerum omnis. Hic molestiae possimus perferendis et exercitationem vero aut quo.",
            "stock": 24,
            "sales": 30
        },
        {
            "id": 118,
            "category_id": 11,
            "reference": "Train Track",
            "width": 37.45,
            "height": 35.01,
            "price": 66.31,
            "thumbnail": "https://marmelab.com/posters/travel-9.jpeg",
            "image": "https://marmelab.com/posters/travel-9.jpeg",
            "description": "Illum ratione ullam est recusandae nam id ut. Numquam mollitia eligendi velit qui sit sed necessitatibus quam. Et molestiae quia. Voluptatem voluptate quae id distinctio fuga eos adipisci. Accusamus voluptatem qui et porro error nulla modi asperiores.",
            "stock": 50,
            "sales": 21
        },
        {
            "id": 119,
            "category_id": 11,
            "reference": "Plane Trees",
            "width": 22.77,
            "height": 11.3,
            "price": 13.72,
            "thumbnail": "https://marmelab.com/posters/travel-10.jpeg",
            "image": "https://marmelab.com/posters/travel-10.jpeg",
            "description": "Beatae blanditiis velit et architecto qui dolor fuga voluptas. Qui est earum nobis voluptatem dolorem nihil et illo. Perspiciatis qui dolor dignissimos nemo reiciendis. Autem sit rerum tempora sit aut. Tempore nobis reprehenderit voluptatem omnis.",
            "stock": 63,
            "sales": 16
        },
        {
            "id": 120,
            "category_id": 12,
            "reference": "Fresh Stream",
            "width": 13.72,
            "height": 28.1,
            "price": 23.82,
            "thumbnail": "https://marmelab.com/posters/water-1.jpeg",
            "image": "https://marmelab.com/posters/water-1.jpeg",
            "description": "Facere nobis commodi ipsam consequuntur nemo saepe laboriosam assumenda. Sint autem voluptates veritatis quisquam. Repellat quia odio sit doloribus aspernatur. Quis aut hic quos molestiae. Qui aliquam dolor qui. Quaerat non perspiciatis nisi.",
            "stock": 133,
            "sales": 12
        },
        {
            "id": 121,
            "category_id": 12,
            "reference": "Reed Line",
            "width": 24.34,
            "height": 38.07,
            "price": 55.31,
            "thumbnail": "https://marmelab.com/posters/water-2.jpeg",
            "image": "https://marmelab.com/posters/water-2.jpeg",
            "description": "Facere enim nam. Ipsam recusandae deleniti quia deleniti fugiat voluptates quo ea. Dolor unde in aut aperiam eum culpa. Sed quia voluptas. Qui eius labore quis est et voluptates.",
            "stock": 140,
            "sales": 21
        },
        {
            "id": 122,
            "category_id": 12,
            "reference": "Mud Tracks",
            "width": 37.05,
            "height": 17.1,
            "price": 36.53,
            "thumbnail": "https://marmelab.com/posters/water-3.jpeg",
            "image": "https://marmelab.com/posters/water-3.jpeg",
            "description": "Et voluptatem dolore qui dolorem quasi dolor. Sed beatae impedit dolorum. Voluptatem voluptas exercitationem sit consequatur.",
            "stock": 47,
            "sales": 19
        },
        {
            "id": 123,
            "category_id": 12,
            "reference": "Beach Gazebo",
            "width": 35.26,
            "height": 37.33,
            "price": 73.82,
            "thumbnail": "https://marmelab.com/posters/water-4.jpeg",
            "image": "https://marmelab.com/posters/water-4.jpeg",
            "description": "Et fugiat eos minus omnis officiis. Necessitatibus beatae voluptatem rerum molestias delectus. Velit ratione maxime consequatur. Amet sapiente numquam blanditiis deserunt voluptas exercitationem minus. Culpa magnam enim aut.",
            "stock": 107,
            "sales": 15
        },
        {
            "id": 124,
            "category_id": 12,
            "reference": "Calm Sea",
            "width": 21.69,
            "height": 31.05,
            "price": 37.37,
            "thumbnail": "https://marmelab.com/posters/water-5.jpeg",
            "image": "https://marmelab.com/posters/water-5.jpeg",
            "description": "Sit ut doloremque ipsa molestias quia. Ducimus ex aut aut in at sit aspernatur odio. Error velit tempore sed quae vel numquam.",
            "stock": 56,
            "sales": 10
        },
        {
            "id": 125,
            "category_id": 12,
            "reference": "Early Bath",
            "width": 28.34,
            "height": 38.65,
            "price": 57.2,
            "thumbnail": "https://marmelab.com/posters/water-6.jpeg",
            "image": "https://marmelab.com/posters/water-6.jpeg",
            "description": "Explicabo nobis tenetur excepturi ut ut perspiciatis. Qui accusantium corporis nisi molestias consequatur temporibus et optio recusandae. Qui error qui voluptates. Dolorum odit est accusantium ad ex ratione quam sint.",
            "stock": 8,
            "sales": 13
        },
        {
            "id": 126,
            "category_id": 12,
            "reference": "Aerial Coast",
            "width": 35.07,
            "height": 31.89,
            "price": 56.37,
            "thumbnail": "https://marmelab.com/posters/water-7.jpeg",
            "image": "https://marmelab.com/posters/water-7.jpeg",
            "description": "Id est eos unde eaque dolorem consectetur. Quis reprehenderit vel commodi quisquam eos. Quo placeat consequatur veritatis ut magni est. Et dolor vel voluptatem suscipit optio voluptatibus. Debitis saepe aspernatur dolores voluptatem eum. Sed cupiditate facilis pariatur voluptatem veniam doloribus assumenda eum.",
            "stock": 110,
            "sales": 13
        },
        {
            "id": 127,
            "category_id": 12,
            "reference": "Canal Street",
            "width": 26.02,
            "height": 15.09,
            "price": 23.64,
            "thumbnail": "https://marmelab.com/posters/water-8.jpeg",
            "image": "https://marmelab.com/posters/water-8.jpeg",
            "description": "Quia illo perspiciatis aut. Molestiae quis et sit nam ratione aut. Iste et sint. Iusto rem aliquid eos. Neque repudiandae ea velit ipsam cupiditate fugit ut possimus.",
            "stock": 115,
            "sales": 30
        },
        {
            "id": 128,
            "category_id": 12,
            "reference": "Artificial Beach",
            "width": 19.45,
            "height": 10.71,
            "price": 11.49,
            "thumbnail": "https://marmelab.com/posters/water-9.jpeg",
            "image": "https://marmelab.com/posters/water-9.jpeg",
            "description": "Perferendis ut aut voluptatum. Eum magnam assumenda impedit laudantium voluptas. Quam quam incidunt dolorem est velit. Adipisci provident autem eos assumenda voluptate. Adipisci odio quo et veniam quasi excepturi in pariatur.",
            "stock": 44,
            "sales": 12
        },
        {
            "id": 129,
            "category_id": 12,
            "reference": "Rainy Day",
            "width": 10.66,
            "height": 31.9,
            "price": 19.72,
            "thumbnail": "https://marmelab.com/posters/water-10.jpeg",
            "image": "https://marmelab.com/posters/water-10.jpeg",
            "description": "Quisquam quos ratione facere sed eos. Quia est atque magni quo. Libero repudiandae perspiciatis est ut ratione quo vitae eos voluptas. Exercitationem cumque quis dolorem commodi. Qui libero in alias repellat ratione doloremque fuga et. Ad reprehenderit est unde repudiandae quis debitis eum debitis sit.",
            "stock": 0,
            "sales": 33
        }
    ];

    return result;
};

export type Product = {
    id: number;
    category_id: number;
    reference: string;
    width: number;
    height: number;
    price: number;
    thumbnail: string;
    image: string;
    description: string;
    stock: number;
    sales: number;
};
